//! Book editor — the app-UI surface over bokai's KFX, EPUB and PDF edit
//! primitives.
//!
//! Covers all three source formats. Each command dispatches on [`SourceKind`]:
//! a **KFX** edit (`kind == "kfx_to_epub"`) is a surgical Ion rewrite of the
//! reader/device file itself; an **EPUB** edit (`epub_to_kfx`) is a surgical
//! OPF/nav/NCX rewrite of the source; a **PDF** edit (`pdf_to_kfx`) is an
//! append-only incremental update of the source. For EPUB and PDF the derived
//! KFX is then regenerated by the conversion queue. `editor_open` reports the
//! source format and an `editable` flag; the UI gates the rail on the reported
//! capability rather than on format names (see [`EditorOpen::panels`]).
//!
//! All three back the same four panels — metadata, cover, images and TOC — but
//! PDF reaches two of them by a different route, and lacks one sub-feature:
//! - **Cover** has its own command ([`editor_set_pdf_cover`]) rather than
//!   reusing `library_set_cover`. The other two formats carry a cover as a
//!   designated *resource* to swap; a PDF's cover **is its first page**, which
//!   is exactly what `pdf_to_kfx` renders for the library tile. So the edit is
//!   to that page — replace it, or insert one when the book opens straight onto
//!   body text.
//! - **Images** shows *pages*, not embedded images. A PDF has no image list to
//!   read — its pages are its images — so the panel renders and exports them
//!   ([`editor_pdf_pages`]).
//! - **Auto-repair TOC** is excluded because PDF has no proposer: a PDF lacking
//!   an outline usually has no links to mine either, so its TOC is hand-authored
//!   (which the panel supports, uniquely for PDF, by adding rows with page
//!   numbers).
//!
//! The save seam ([`commit_edited_source`]) picks the format's path:
//! [`commit_edited_kfx`] rewrites the KFX in place preserving the frozen
//! `kfx_sha256` device identity; [`commit_replaced_source`] rewrites a source
//! EPUB/PDF, and the follow-up reconvert re-freezes `kfx_sha256` via COALESCE —
//! so device identity is preserved for every format.

use std::collections::HashSet;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use tauri::{AppHandle, Emitter, State};
use tauri_plugin_dialog::DialogExt;
use tokio::sync::oneshot;

use bokai::formats::epub::image_extract as epub_image;
use bokai::formats::epub::metadata_edit::{self as epub_meta, MetadataPatch as EpubMetadataPatch};
use bokai::formats::epub::toc_repair as epub_toc;
use bokai::formats::kfx::image_extract;
use bokai::formats::kfx::metadata_edit::{self, MetadataPatch as KfxMetadataPatch};
use bokai::formats::kfx::toc_repair::{self, TocEntry as KfxTocEntry};
use bokai::formats::pdf::cover::{self as pdf_cover, CoverMode};
use bokai::formats::pdf::metadata_edit::{self as pdf_meta, MetadataPatch as PdfMetadataPatch};
use bokai::formats::pdf::toc_repair as pdf_toc;
use bokai::import::pdf::PdfOutlineItem;
use bokai::model::TocEntry as EpubTocEntry;
use bokai::validate::source::toc as toc_validate;

use crate::commands::library::SetCoverResult;
use crate::library::{authors, db, db::BookRow};
use crate::state::AppState;

/// Which editable source format a book carries, with its on-disk path. Each arm
/// takes a different surgical-edit and save-seam path: KFX rewrites Ion in the
/// reader/device file itself; EPUB rewrites the OPF/nav/NCX source; PDF appends
/// an incremental update to the source. EPUB and PDF then re-derive the KFX via
/// reconvert.
#[derive(Clone, Copy, PartialEq, Eq)]
enum SourceKind {
    Kfx,
    Epub,
    Pdf,
}

/// Resolve a book's editable source: its format + on-disk path. Errors for an
/// unrecognized source format, or when the source file is missing.
fn require_editable_source(row: &BookRow) -> Result<(SourceKind, String), String> {
    match source_format(row.kind.as_deref()).as_str() {
        "kfx" => row
            .kfx_path
            .clone()
            .map(|p| (SourceKind::Kfx, p))
            .ok_or_else(|| "this book has no KFX file yet".to_string()),
        "epub" => row
            .epub_path
            .clone()
            .map(|p| (SourceKind::Epub, p))
            .ok_or_else(|| "this book has no EPUB file yet".to_string()),
        "pdf" => row
            .pdf_path
            .clone()
            .map(|p| (SourceKind::Pdf, p))
            .ok_or_else(|| "this book has no PDF file yet".to_string()),
        other => Err(format!(
            "the editor edits KFX-, EPUB- and PDF-source books; this is a {other}-source book"
        )),
    }
}

/// Which editor panels an editable source can back, so the UI gates the rail on
/// capability rather than hardcoding format names.
///
/// All three source formats now back all four, though they get there by
/// different routes — a PDF's `cover` is its first page rather than a swappable
/// resource (see the module docs). The rail's fifth item, `text`, is deliberately
/// absent: no format has the surgical text-replace primitive behind it.
fn editor_panels() -> Vec<String> {
    ["metadata", "toc", "cover", "images"]
        .into_iter()
        .map(str::to_string)
        .collect()
}

/// Fetch a book row and resolve its editable source (kind + path) — the shared
/// preamble of every editor command.
async fn editor_source(
    state: &State<'_, AppState>,
    book_id: i64,
) -> Result<(SourceKind, String), String> {
    let conn = state.db.lock().await;
    let row = db::get_book(&conn, book_id)
        .map_err(|e| e.to_string())?
        .ok_or_else(|| format!("no book with id {book_id}"))?;
    require_editable_source(&row)
}

/// Source format a book was imported *from*, from its conversion `kind`
/// (`"<source>_to_<target>"`): `"kfx"`, `"epub"`, or `"pdf"`. Mirrors the
/// frontend `sourceFormat()` helper.
fn source_format(kind: Option<&str>) -> String {
    kind.unwrap_or("epub_to_kfx")
        .split("_to_")
        .next()
        .unwrap_or("epub")
        .to_string()
}

/// TOC health from the source bytes — surfaced as the top-bar validate chip and
/// (later) the TOC panel header. Mirrors `validate::source::toc::TocAudit`.
#[derive(Serialize)]
pub struct EditorToc {
    /// `"OK"` | `"SUSPECT"` | `"SPARSE"`.
    pub verdict: String,
    pub nav_count: usize,
    pub nav_chapters: usize,
    pub contents_links: usize,
    pub headings: usize,
    pub section_heads: usize,
}

/// Current metadata for the metadata panel. `author` is the display string
/// (`"Jane Smith & John Doe"`), parsed back into an ordered list on save.
#[derive(Serialize)]
pub struct EditorMetadata {
    pub title: String,
    pub author: String,
    pub language: String,
    pub publisher: Option<String>,
    pub published_at: Option<String>,
    pub asin: Option<String>,
}

/// The editor's opening snapshot for one book — what the shell renders from.
#[derive(Serialize)]
pub struct EditorOpen {
    pub book_id: i64,
    /// Source format: `"kfx"` | `"epub"` | `"pdf"`.
    pub format: String,
    /// True when the source is editable — i.e. the book's source file is on disk
    /// and its format has a write path. All three formats qualify now; a missing
    /// source file does not.
    pub editable: bool,
    /// Which panels this source can back — the rail enables exactly these, and
    /// nothing when the book isn't editable. See [`editor_panels`].
    pub panels: Vec<String>,
    pub metadata: EditorMetadata,
    pub has_cover: bool,
    /// `None` when the TOC verdict couldn't be computed (read or parse error).
    pub toc: Option<EditorToc>,
}

/// Load the opening snapshot for the editor shell.
#[tauri::command]
pub async fn editor_open(state: State<'_, AppState>, book_id: i64) -> Result<EditorOpen, String> {
    let row = {
        let conn = state.db.lock().await;
        db::get_book(&conn, book_id)
            .map_err(|e| e.to_string())?
            .ok_or_else(|| format!("no book with id {book_id}"))?
    };
    let format = source_format(row.kind.as_deref());
    let source = require_editable_source(&row).ok();
    let editable = source.is_some();
    let panels = if editable {
        editor_panels()
    } else {
        Vec::new()
    };

    // TOC verdict from the *source* bytes. Off the async thread — it's a full
    // container/zip/PDF parse.
    let toc = match source {
        Some((kind, path)) => tokio::task::spawn_blocking(move || compute_toc(&path, kind))
            .await
            .map_err(|e| e.to_string())?,
        None => None,
    };

    Ok(EditorOpen {
        book_id,
        format,
        editable,
        panels,
        metadata: EditorMetadata {
            title: row.title.clone(),
            author: row.author.clone(),
            language: row.language.clone(),
            publisher: row.publisher.clone(),
            published_at: row.published_at.clone(),
            asin: row.asin.clone(),
        },
        has_cover: row.cover_path.is_some(),
        toc,
    })
}

/// Fields the metadata panel submits. All are always present (the panel is
/// populated from the current values); an empty publisher/date/asin clears that
/// field.
#[derive(Deserialize)]
pub struct MetadataForm {
    pub title: String,
    /// Raw author line (`"A & B"`) — parsed and canonicalized backend-side.
    pub author: String,
    pub language: String,
    pub publisher: Option<String>,
    pub published_at: Option<String>,
    pub asin: Option<String>,
}

/// Write edited metadata into the KFX source *and* the library row.
///
/// The KFX write is the editor's durable value-add: a surgical
/// `book_metadata`/`metadata` patch, no whole-book re-encode. The row sync keeps
/// the library UI (title/author/…) in step and reuses the metadata modal's exact
/// canonicalize → persist → file-rename path via [`apply_metadata_patch`].
#[tauri::command]
pub async fn editor_save_metadata(
    app: AppHandle,
    state: State<'_, AppState>,
    book_id: i64,
    form: MetadataForm,
) -> Result<BookRow, String> {
    let row = {
        let conn = state.db.lock().await;
        db::get_book(&conn, book_id)
            .map_err(|e| e.to_string())?
            .ok_or_else(|| format!("no book with id {book_id}"))?
    };
    let (kind, path) = require_editable_source(&row)?;

    // Canonicalize the human fields once so the source artifact and the DB row
    // agree (author list flip/split, language code harmonize, empty → cleared).
    let title = form.title.trim().to_string();
    if title.is_empty() {
        return Err("title cannot be empty".into());
    }
    let author_names = authors::parse_input(&form.author);
    let language = crate::library::lang::normalize(&form.language);
    let publisher = trim_opt(form.publisher);
    let published_at = trim_opt(form.published_at);
    let asin = trim_opt(form.asin);

    // 1) Surgical metadata write into the source (KFX Ion / EPUB OPF), then
    //    commit it in place. Clone the canonical fields into the blocking task so
    //    the originals stay for the DB-row sync below.
    let src = path.clone();
    let (c_title, c_authors, c_lang, c_pub, c_date, c_asin) = (
        title.clone(),
        author_names.clone(),
        language.clone(),
        publisher.clone(),
        published_at.clone(),
        asin.clone(),
    );
    let new_bytes = tokio::task::spawn_blocking(move || -> Result<Vec<u8>, String> {
        let bytes = std::fs::read(&src).map_err(|e| format!("read {src}: {e}"))?;
        match kind {
            SourceKind::Kfx => {
                let patch = KfxMetadataPatch {
                    title: Some(c_title),
                    authors: Some(c_authors),
                    language: Some(c_lang),
                    publisher: c_pub,
                    issue_date: c_date,
                    asin: c_asin,
                };
                metadata_edit::edit_metadata(&bytes, &patch).map_err(|e| e.to_string())
            }
            SourceKind::Epub => {
                let patch = EpubMetadataPatch {
                    title: Some(c_title),
                    authors: Some(c_authors),
                    language: Some(c_lang),
                    publisher: c_pub,
                    date: c_date,
                    asin: c_asin,
                };
                epub_meta::edit_metadata(&bytes, &patch).map_err(|e| e.to_string())
            }
            // PDF's `/Info` has no language/publisher/ASIN key, so those reach
            // only the library row (the patch accepts them and ignores them —
            // see `bokai::formats::pdf::metadata_edit`). Title/author/date are durable.
            SourceKind::Pdf => {
                let patch = PdfMetadataPatch {
                    title: Some(c_title),
                    authors: Some(c_authors),
                    language: Some(c_lang),
                    publisher: c_pub,
                    date: c_date,
                };
                pdf_meta::edit_metadata(&bytes, &patch).map_err(|e| e.to_string())
            }
        }
    })
    .await
    .map_err(|e| e.to_string())??;
    commit_edited_source(&state, book_id, kind, &path, new_bytes).await?;

    // 2) Sync the library row. ASIN isn't part of db::MetadataPatch, so set it
    //    separately; blank romaji triggers the modal path's self-heal regenerate
    //    (the title/author may have changed under it).
    if let Some(asin) = asin.as_deref() {
        let conn = state.db.lock().await;
        db::set_asin(&conn, book_id, asin).map_err(|e| e.to_string())?;
    }
    let patch = db::MetadataPatch {
        title,
        author: authors::join_display(&author_names),
        language,
        ppd: row.ppd.clone(),
        writing_mode: row.writing_mode.clone(),
        publisher,
        published_at,
        series_name: row.series_name.clone(),
        series_index: row.series_index,
        tags: row.tags.clone(),
        title_romaji: String::new(),
        author_romaji: String::new(),
    };
    let updated =
        crate::commands::library::apply_metadata_patch(&app, &state, book_id, patch).await?;

    // 3) Regenerate the derived EPUB from the edited KFX and drop the reader
    //    cache so a re-open reflects the change.
    let _ = state.queue.enqueue_reconvert(book_id).await;
    crate::commands::reader::evict_reader(&state, book_id).await;

    Ok(updated)
}

// --- cover (PDF) ----------------------------------------------------------

/// Give a PDF-source book a cover page.
///
/// The PDF analog of `library_set_cover`, and deliberately a separate command:
/// EPUB and KFX swap a designated cover *resource*, but a PDF's cover **is its
/// first page**, so this edits that page. `mode` is `"replace"` (overwrite the
/// existing first page) or `"insert"` (add one in front, for a book that opens
/// straight onto body text).
///
/// Also writes the picked image as the library's sidecar cover, so the gallery
/// tile updates immediately rather than waiting on the reconvert — and the
/// PDF→KFX worker prefers that sidecar over its own page-1 render, so the two
/// agree. Then re-derives the KFX and refreshes the row.
///
/// Returns [`SetCoverResult`], the same contract as `library_set_cover`, so the
/// editor's Cover panel drives both formats through one path.
#[tauri::command]
pub async fn editor_set_pdf_cover(
    app: AppHandle,
    state: State<'_, AppState>,
    book_id: i64,
    src_path: String,
    mode: String,
) -> Result<SetCoverResult, String> {
    let mode = match mode.as_str() {
        "replace" => CoverMode::Replace,
        "insert" => CoverMode::Insert,
        other => return Err(format!("unknown cover mode {other:?}")),
    };
    let row = {
        let conn = state.db.lock().await;
        db::get_book(&conn, book_id)
            .map_err(|e| e.to_string())?
            .ok_or_else(|| format!("no book with id {book_id}"))?
    };
    let (kind, path) = require_editable_source(&row)?;
    if kind != SourceKind::Pdf {
        return Err("this command is for PDF-source books only".into());
    }

    let image = match std::fs::read(&src_path) {
        Ok(b) => b,
        Err(e) => {
            return Ok(SetCoverResult::Failed {
                error: format!("read {src_path}: {e}"),
            });
        }
    };
    let Some(ext) = crate::commands::library::sniff_image_format(&image) else {
        return Ok(SetCoverResult::Failed {
            error: "unsupported image format (expected JPG, PNG, or WebP)".into(),
        });
    };

    // 1) Write the cover page into the PDF and commit it.
    let (src, img) = (path.clone(), image.clone());
    let edited = tokio::task::spawn_blocking(move || -> Result<Vec<u8>, String> {
        let bytes = std::fs::read(&src).map_err(|e| format!("read {src}: {e}"))?;
        pdf_cover::set_cover_page(&bytes, &img, mode).map_err(|e| e.to_string())
    })
    .await
    .map_err(|e| e.to_string())?;
    let new_bytes = match edited {
        Ok(b) => b,
        Err(error) => return Ok(SetCoverResult::Failed { error }),
    };
    commit_edited_source(&state, book_id, kind, &path, new_bytes).await?;

    // 2) Point the library at the same image, so the tile matches the book's new
    //    first page without waiting for the reconvert to render it.
    let out = state.paths.cover(&row.sha256, ext);
    std::fs::write(&out, &image).map_err(|e| format!("write {}: {e}", out.display()))?;
    let out_str = out.to_string_lossy().to_string();
    {
        let conn = state.db.lock().await;
        db::set_cover_path(&conn, book_id, &out_str).map_err(|e| e.to_string())?;
    }
    let _ = crate::library::thumbnail::ensure_thumbnail(&state.paths, &row.sha256, &out);
    // A previous cover under a different extension would otherwise linger.
    if let Some(old) = row.cover_path.as_deref()
        && old != out_str.as_str()
    {
        let _ = std::fs::remove_file(old);
    }

    // 3) Re-derive the KFX from the edited PDF and refresh the UI.
    let _ = state.queue.enqueue_reconvert(book_id).await;
    crate::commands::reader::evict_reader(&state, book_id).await;

    if let Ok(Some(updated)) = {
        let conn = state.db.lock().await;
        db::get_book(&conn, book_id)
    } {
        let _ = app.emit("library:row-updated", &updated);
    }
    Ok(SetCoverResult::Updated {
        cover_path: out_str,
    })
}

/// One TOC entry crossing the wire — the full `TocEntry` tree, nesting intact.
/// A repair mirrors the book's own structure: a flat Contents page yields a flat
/// TOC, a Part→chapter Contents page yields a nested one. We never flatten a
/// nested source or nest a flat one.
#[derive(Serialize, Deserialize, Clone)]
pub struct TocEntryDto {
    pub label: String,
    /// KFX target — the `$155` element id. `0` for an EPUB entry (which targets
    /// by `href`). The frontend passes this back opaquely; it only edits labels.
    #[serde(default)]
    pub eid: i64,
    /// EPUB target — an absolute zip-path href (e.g. `"OEBPS/c1.xhtml#ch1"`).
    /// Empty for a KFX entry. Round-trips through the frontend untouched.
    #[serde(default)]
    pub href: String,
    /// PDF target — a **1-based** page number, i.e. what the user types and what
    /// the panel shows. `0` for a KFX/EPUB entry. Unlike `eid`/`href` this is
    /// user-editable, because a hand-authored PDF TOC is the whole point: the
    /// boundary converts to/from the 0-based `page_index` the primitive uses.
    #[serde(default)]
    pub page: usize,
    #[serde(default)]
    pub children: Vec<TocEntryDto>,
}

impl TocEntryDto {
    /// KFX proposer `TocEntry` → wire DTO, recursively.
    fn from_kfx(e: &KfxTocEntry) -> Self {
        Self {
            label: e.label.clone(),
            eid: e.eid,
            href: String::new(),
            page: 0,
            children: e.children.iter().map(Self::from_kfx).collect(),
        }
    }

    /// Wire DTO → KFX `TocEntry` for `kfx::toc_repair::set_toc`, trimming labels.
    fn into_kfx(self) -> KfxTocEntry {
        KfxTocEntry {
            label: self.label.trim().to_string(),
            eid: self.eid,
            children: self.children.into_iter().map(Self::into_kfx).collect(),
        }
    }

    /// EPUB proposer `TocEntry` (title + href) → wire DTO, recursively.
    fn from_epub(e: &EpubTocEntry) -> Self {
        Self {
            label: e.title.clone(),
            eid: 0,
            href: e.href.clone(),
            page: 0,
            children: e.children.iter().map(Self::from_epub).collect(),
        }
    }

    /// PDF outline item → wire DTO. `page_index` is 0-based; the panel shows and
    /// edits 1-based page numbers.
    fn from_pdf(e: &PdfOutlineItem) -> Self {
        Self {
            label: e.title.clone(),
            eid: 0,
            href: String::new(),
            page: e.page_index + 1,
            children: e.children.iter().map(Self::from_pdf).collect(),
        }
    }

    /// Wire DTO → `PdfOutlineItem` for `pdf::toc_repair::set_toc`. A `page` of 0
    /// (unset by the panel) clamps to page 1 rather than underflowing; anything
    /// past the last page is rejected by the primitive, which names the entry.
    fn into_pdf(self) -> PdfOutlineItem {
        PdfOutlineItem {
            title: self.label.trim().to_string(),
            page_index: self.page.saturating_sub(1),
            children: self.children.into_iter().map(Self::into_pdf).collect(),
        }
    }

    /// Wire DTO → EPUB `TocEntry` for `epub::toc_repair::set_toc`, trimming labels.
    fn into_epub(self) -> EpubTocEntry {
        let mut t = EpubTocEntry::new(self.label.trim(), self.href);
        t.children = self.children.into_iter().map(Self::into_epub).collect();
        t
    }
}

/// True if any entry in the tree has a blank label — a rejected edit (`set_toc`
/// would emit an unlabeled nav unit).
fn any_blank_label(entries: &[TocEntryDto]) -> bool {
    entries
        .iter()
        .any(|e| e.label.trim().is_empty() || any_blank_label(&e.children))
}

/// Full state for the TOC panel: the current declared TOC, the verdict, and a
/// proposed chapter list derived from the book's own in-book Contents page.
#[derive(Serialize)]
pub struct EditorTocDetail {
    /// `"OK"` | `"SUSPECT"` | `"SPARSE"`.
    pub verdict: String,
    pub nav_count: usize,
    pub nav_chapters: usize,
    /// The currently-declared TOC entry labels (flattened) — what's wrong (or
    /// right) today.
    pub current: Vec<String>,
    /// The editable tree the panel starts from. For KFX/EPUB it's a *proposal*
    /// derived from the densest in-book Contents-page link cluster, in document
    /// order with the book's own nesting preserved. For PDF there is no proposer,
    /// so it's the book's **existing** outline (empty when it has none — the
    /// "PDF lacks a TOC" case, where the panel starts blank and the user adds
    /// rows). Empty otherwise means none could be derived (see `note`).
    pub proposed: Vec<TocEntryDto>,
    /// Set when no proposal could be derived, explaining why.
    pub note: Option<String>,
    /// `Some(n)` for a PDF source: entries target 1-based page numbers in `1..=n`,
    /// and the panel switches to hand-authoring mode (page inputs + Add entry,
    /// no auto-repair). `None` for KFX/EPUB, whose targets are opaque.
    pub page_count: Option<usize>,
    /// True when the format has an automatic proposer (`editor_repair_toc`).
    /// False for PDF — a PDF lacking an outline usually has no links to mine.
    pub can_auto_repair: bool,
}

/// Read the TOC panel state (verdict + current + proposal). Lazy — the frontend
/// calls it when the TOC panel is first opened, not on every editor open.
#[tauri::command]
pub async fn editor_toc(
    state: State<'_, AppState>,
    book_id: i64,
) -> Result<EditorTocDetail, String> {
    let (kind, path) = editor_source(&state, book_id).await?;
    tokio::task::spawn_blocking(move || read_toc_detail(&path, kind))
        .await
        .map_err(|e| e.to_string())?
}

/// Write a reviewed TOC (`entries`, in order) into the KFX and re-derive. The
/// user-facing path: the panel shows the proposal, the user tweaks/removes rows,
/// then applies. Returns the refreshed panel state (verdict should flip to OK).
#[tauri::command]
pub async fn editor_set_toc(
    state: State<'_, AppState>,
    book_id: i64,
    entries: Vec<TocEntryDto>,
) -> Result<EditorTocDetail, String> {
    let (kind, path) = editor_source(&state, book_id).await?;
    if entries.is_empty() {
        return Err("a table of contents needs at least one entry".into());
    }
    if any_blank_label(&entries) {
        return Err("every table-of-contents entry needs a label".into());
    }

    // Preserve the tree exactly — no flatten, no re-nest — and write it via the
    // source format's own primitive (KFX targets by eid, EPUB by href).
    let src = path.clone();
    let new_bytes = tokio::task::spawn_blocking(move || -> Result<Vec<u8>, String> {
        let bytes = std::fs::read(&src).map_err(|e| format!("read {src}: {e}"))?;
        match kind {
            SourceKind::Kfx => {
                let toc: Vec<KfxTocEntry> =
                    entries.into_iter().map(TocEntryDto::into_kfx).collect();
                toc_repair::set_toc(&bytes, &toc).map_err(|e| e.to_string())
            }
            SourceKind::Epub => {
                let toc: Vec<EpubTocEntry> =
                    entries.into_iter().map(TocEntryDto::into_epub).collect();
                epub_toc::set_toc(&bytes, &toc).map_err(|e| e.to_string())
            }
            SourceKind::Pdf => {
                let toc: Vec<PdfOutlineItem> =
                    entries.into_iter().map(TocEntryDto::into_pdf).collect();
                pdf_toc::set_toc(&bytes, &toc).map_err(|e| e.to_string())
            }
        }
    })
    .await
    .map_err(|e| e.to_string())??;

    commit_edited_source(&state, book_id, kind, &path, new_bytes).await?;
    let _ = state.queue.enqueue_reconvert(book_id).await;
    crate::commands::reader::evict_reader(&state, book_id).await;

    let p = path.clone();
    tokio::task::spawn_blocking(move || read_toc_detail(&p, kind))
        .await
        .map_err(|e| e.to_string())?
}

/// One-click repair: derive the chapter list and write it in a single pass
/// (`propose + set`), for a user who trusts the proposal without reviewing.
#[tauri::command]
pub async fn editor_repair_toc(
    state: State<'_, AppState>,
    book_id: i64,
) -> Result<EditorTocDetail, String> {
    let (kind, path) = editor_source(&state, book_id).await?;

    let src = path.clone();
    let new_bytes = tokio::task::spawn_blocking(move || -> Result<Vec<u8>, String> {
        let bytes = std::fs::read(&src).map_err(|e| format!("read {src}: {e}"))?;
        match kind {
            SourceKind::Kfx => toc_repair::repair_toc(&bytes).map_err(|e| e.to_string()),
            SourceKind::Epub => epub_toc::repair_toc(&bytes).map_err(|e| e.to_string()),
            // No PDF proposer exists (see the module docs), so there is nothing
            // to auto-derive from. The panel hides the button via
            // `EditorTocDetail::can_auto_repair`; this is the belt-and-braces arm.
            SourceKind::Pdf => Err(
                "a PDF's table of contents can't be derived automatically — add \
                 the entries by hand"
                    .to_string(),
            ),
        }
    })
    .await
    .map_err(|e| e.to_string())??;

    commit_edited_source(&state, book_id, kind, &path, new_bytes).await?;
    let _ = state.queue.enqueue_reconvert(book_id).await;
    crate::commands::reader::evict_reader(&state, book_id).await;

    let p = path.clone();
    tokio::task::spawn_blocking(move || read_toc_detail(&p, kind))
        .await
        .map_err(|e| e.to_string())?
}

// --- images ---------------------------------------------------------------

/// One embedded image for the Images panel (KFX/EPUB): identity + dimensions +
/// an on-disk preview copy the webview loads through the asset protocol. The
/// panel offers extract/export only; image *replacement* is a later tier.
#[derive(Serialize)]
pub struct EditorImage {
    /// Position in the source's image list — the stable key
    /// [`editor_export_image`] re-resolves against (the list is read-only and
    /// deterministically sorted by the extractor).
    pub index: usize,
    /// Display name, in the source format's own terms — see [`RawImage`].
    pub resource_name: String,
    /// Lowercase extension, no dot: `"jpg"`/`"png"`/`"gif"`/`"webp"`/`"bmp"`.
    pub ext: String,
    pub width: Option<u32>,
    pub height: Option<u32>,
    /// True for the book's declared cover, matched by backing bytes. (PDF never
    /// reaches this struct — see [`EditorPdfPage`].)
    pub is_cover: bool,
    pub byte_len: usize,
    /// Absolute path to a decoded preview copy on disk, for `convertFileSrc`.
    pub preview_path: String,
}

/// List every embedded image, writing a preview copy of each into a per-book
/// cache dir the webview can load. Read-only — the source is never touched.
///
/// KFX and EPUB only: a PDF has no embedded-image list, so its Images panel
/// takes the page-export path ([`editor_pdf_pages`]) and never calls this.
#[tauri::command]
pub async fn editor_images(
    state: State<'_, AppState>,
    book_id: i64,
) -> Result<Vec<EditorImage>, String> {
    let (kind, path) = editor_source(&state, book_id).await?;
    // A fresh dir per book keeps only the open book's previews on disk.
    let preview_dir = state
        .paths
        .root
        .join("editor-images")
        .join(book_id.to_string());
    tokio::task::spawn_blocking(move || extract_images_with_previews(&path, kind, &preview_dir))
        .await
        .map_err(|e| e.to_string())?
}

/// Export one embedded image to a user-picked path (save dialog defaulting to
/// `<resource_name>.<ext>`). Returns the saved path, or `None` if cancelled.
#[tauri::command]
pub async fn editor_export_image(
    app: AppHandle,
    state: State<'_, AppState>,
    book_id: i64,
    index: usize,
) -> Result<Option<String>, String> {
    let (kind, path) = editor_source(&state, book_id).await?;
    // Re-extract and pick the one image by its stable index (the source is
    // unchanged between listing and export, so the sorted order is identical).
    let src = path.clone();
    let (bytes, default_name) =
        tokio::task::spawn_blocking(move || -> Result<(Vec<u8>, String), String> {
            let images = extract_images(&src, kind)?;
            let img = images
                .get(index)
                .ok_or_else(|| "that image is no longer present".to_string())?;
            Ok((
                img.bytes.clone(),
                format!("{}.{}", sanitize_filename(&img.name), img.ext),
            ))
        })
        .await
        .map_err(|e| e.to_string())??;

    let (tx, rx) = oneshot::channel();
    app.dialog()
        .file()
        .set_file_name(default_name)
        .save_file(move |path| {
            let _ = tx.send(path);
        });
    let Some(dest) = rx.await.map_err(|e| e.to_string())? else {
        return Ok(None); // cancelled
    };
    let dest = PathBuf::from(dest.to_string());
    std::fs::write(&dest, &bytes).map_err(|e| format!("write {}: {e}", dest.display()))?;
    Ok(Some(dest.to_string_lossy().to_string()))
}

/// How many images an [`editor_export_images`] run wrote, and where.
#[derive(Serialize)]
pub struct ExportImagesResult {
    pub dir: String,
    pub count: usize,
}

/// Export every embedded image into `dir`, each named `<resource_name>.<ext>`
/// with a numeric suffix on any name collision.
#[tauri::command]
pub async fn editor_export_images(
    state: State<'_, AppState>,
    book_id: i64,
    dir: String,
) -> Result<ExportImagesResult, String> {
    let (kind, path) = editor_source(&state, book_id).await?;
    let dest_dir = PathBuf::from(&dir);
    let count = tokio::task::spawn_blocking(move || -> Result<usize, String> {
        let images = extract_images(&path, kind)?;
        std::fs::create_dir_all(&dest_dir)
            .map_err(|e| format!("create {}: {e}", dest_dir.display()))?;
        let mut used: HashSet<String> = HashSet::new();
        for img in &images {
            let stem = sanitize_filename(&img.name);
            let mut fname = format!("{stem}.{}", img.ext);
            let mut i = 1;
            while !used.insert(fname.clone()) {
                fname = format!("{stem}-{i}.{}", img.ext);
                i += 1;
            }
            let path = dest_dir.join(&fname);
            std::fs::write(&path, &img.bytes)
                .map_err(|e| format!("write {}: {e}", path.display()))?;
        }
        Ok(images.len())
    })
    .await
    .map_err(|e| e.to_string())??;
    Ok(ExportImagesResult { dir, count })
}

/// One extracted image, normalized across the source formats that *have* an
/// embedded-image list — KFX and EPUB. `name` is a display / export stem: a KFX
/// `resource_name`, or an EPUB member's filename stem.
struct RawImage {
    name: String,
    ext: String,
    width: Option<u32>,
    height: Option<u32>,
    is_cover: bool,
    bytes: Vec<u8>,
}

/// Extract every embedded image from the source, normalized to [`RawImage`] and
/// deterministically ordered (so an index is a stable handle across calls). Sync
/// — call inside `spawn_blocking`.
fn extract_images(source_path: &str, kind: SourceKind) -> Result<Vec<RawImage>, String> {
    let bytes = std::fs::read(source_path).map_err(|e| format!("read {source_path}: {e}"))?;
    let out = match kind {
        SourceKind::Kfx => image_extract::kfx_extract_images(&bytes)
            .map_err(|e| e.to_string())?
            .into_iter()
            .map(|i| RawImage {
                name: i.resource_name,
                ext: i.ext.to_string(),
                width: i.width,
                height: i.height,
                is_cover: i.is_cover,
                bytes: i.bytes,
            })
            .collect(),
        SourceKind::Epub => epub_image::epub_extract_images(&bytes)
            .map_err(|e| e.to_string())?
            .into_iter()
            .map(|i| RawImage {
                name: image_stem(&i.path),
                ext: i.ext.to_string(),
                width: i.width,
                height: i.height,
                is_cover: i.is_cover,
                bytes: i.bytes,
            })
            .collect(),
        // A PDF has no embedded-image list worth showing: its pages *are* its
        // images, so the panel takes the page-export path instead
        // ([`editor_pdf_pages`]) and never calls this.
        SourceKind::Pdf => {
            return Err("a PDF's images are its pages — export them instead".to_string());
        }
    };
    Ok(out)
}

/// The filename stem of a zip member path — `"OEBPS/img/fig1.jpg"` → `"fig1"` —
/// used as an EPUB image's display / export name (the extension is added back).
fn image_stem(path: &str) -> String {
    let base = path.rsplit('/').next().unwrap_or(path);
    base.rsplit_once('.')
        .map(|(s, _)| s)
        .unwrap_or(base)
        .to_string()
}

/// Extract every image and materialize a preview copy on disk. Sync (reads +
/// parses the source, writes files); call inside `spawn_blocking`.
fn extract_images_with_previews(
    source_path: &str,
    kind: SourceKind,
    preview_dir: &Path,
) -> Result<Vec<EditorImage>, String> {
    let images = extract_images(source_path, kind)?;

    let _ = std::fs::remove_dir_all(preview_dir); // stale previews from a prior open
    std::fs::create_dir_all(preview_dir)
        .map_err(|e| format!("create {}: {e}", preview_dir.display()))?;

    let mut out = Vec::with_capacity(images.len());
    for (index, img) in images.iter().enumerate() {
        // Index-prefixed so two resources with the same sanitized name (e.g.
        // both non-ASCII) still land on distinct preview files.
        let fname = format!("{index}-{}.{}", sanitize_filename(&img.name), img.ext);
        let path = preview_dir.join(&fname);
        std::fs::write(&path, &img.bytes).map_err(|e| format!("write {}: {e}", path.display()))?;
        out.push(EditorImage {
            index,
            resource_name: img.name.clone(),
            ext: img.ext.clone(),
            width: img.width,
            height: img.height,
            is_cover: img.is_cover,
            byte_len: img.bytes.len(),
            preview_path: path.to_string_lossy().to_string(),
        });
    }
    Ok(out)
}

// --- PDF page export ------------------------------------------------------
//
// The PDF arm of the Images panel. KFX and EPUB carry a list of embedded images
// to pull out; a PDF's images *are* its pages, so "extract an image" here means
// "export this page as one" — `PDFPage.draw(with:to:)`, exactly Preview's
// Export As.
//
// Rendering rather than digging Image XObjects out of the page's `/Resources` is
// the only honest reading of it. A page that draws a scan *plus* a page number
// is one image — the page — and handing back the scan alone would silently drop
// the number. It also sidesteps the codecs: real books lean on JPEG 2000, CCITT
// and JBIG2, none of which have a decoder in this codebase, and all of which
// PDFKit renders.

/// One page offered for export. Sizes are in PDF points (`/Rotate` applied), so
/// the panel can lay out an aspect-correct card and show what a given DPI will
/// produce, before any pixels are rendered.
#[derive(Serialize)]
pub struct EditorPdfPage {
    /// 1-based page number — the handle [`editor_export_pdf_page`] takes.
    pub page: usize,
    pub width_pt: f32,
    pub height_pt: f32,
}

/// List a PDF's pages for the Images panel. Thumbnails are *not* rendered here:
/// the panel asks for each one lazily (`reader_pdf_page`) as its card scrolls
/// into view, which keeps opening a 570-page book instant.
#[tauri::command]
pub async fn editor_pdf_pages(
    state: State<'_, AppState>,
    book_id: i64,
) -> Result<Vec<EditorPdfPage>, String> {
    let (kind, path) = editor_source(&state, book_id).await?;
    if kind != SourceKind::Pdf {
        return Err("this book's source isn't a PDF".to_string());
    }
    tokio::task::spawn_blocking(move || -> Result<Vec<EditorPdfPage>, String> {
        Ok(probe_pdf_pages(&path)?
            .into_iter()
            .enumerate()
            .map(|(i, p)| EditorPdfPage {
                page: i + 1,
                width_pt: p.width,
                height_pt: p.height,
            })
            .collect())
    })
    .await
    .map_err(|e| e.to_string())?
}

/// Read a PDF's page geometry. Sync — call inside `spawn_blocking`.
fn probe_pdf_pages(path: &str) -> Result<Vec<bokai::import::pdf::PdfPage>, String> {
    let bytes = std::fs::read(path).map_err(|e| format!("read {path}: {e}"))?;
    bokai::import::pdf::probe_pdf(bytes)
        .map(|d| d.pages)
        .map_err(|e| e.to_string())
}

/// How a page is encoded on export. JPEG for scans (already JPEG inside the PDF,
/// so PNG only inflates them); PNG for text and line art, where JPEG rings
/// around every glyph edge.
#[derive(Deserialize, Clone, Copy, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum PageFormat {
    Jpeg,
    Png,
}

impl PageFormat {
    fn ext(self) -> &'static str {
        match self {
            PageFormat::Jpeg => "jpg",
            PageFormat::Png => "png",
        }
    }
}

/// JPEG quality for an exported page. Above the library cover's 85: this is the
/// artifact the user asked for, not a thumbnail, and nothing re-encodes it after.
const PAGE_EXPORT_JPEG_QUALITY: u8 = 90;

/// Pixel width for a page `width_pt` points wide rendered at `dpi`. A PDF point
/// is 1/72", so this is exactly what the DPI asks for.
///
/// Clamped at both ends: the rasterizer refuses a bitmap wider than a `u16`, and
/// the upper bound still clears 600 dpi on a page the size of an A0 poster. A
/// degenerate zero-width page floors at 1 rather than producing an empty bitmap.
fn export_width_px(width_pt: f32, dpi: u32) -> u32 {
    let px = width_pt * dpi as f32 / 72.0;
    if !px.is_finite() {
        return 1;
    }
    (px.round() as i64).clamp(1, 20_000) as u32
}

/// Render one page to image bytes at `dpi`. `page` is 1-based. Sync — call
/// inside `spawn_blocking`.
fn render_page(
    pdf: &[u8],
    pages: &[bokai::import::pdf::PdfPage],
    page: usize,
    dpi: u32,
    format: PageFormat,
) -> Result<Vec<u8>, String> {
    let geom = pages
        .get(page.wrapping_sub(1))
        .ok_or_else(|| format!("this PDF has no page {page}"))?;
    let width_px = export_width_px(geom.width, dpi);
    let index = page - 1;
    match format {
        PageFormat::Jpeg => bokai::formats::pdf::render::render_pdf_page_jpeg(
            pdf,
            index,
            width_px,
            PAGE_EXPORT_JPEG_QUALITY,
        ),
        PageFormat::Png => bokai::formats::pdf::render::render_pdf_page_png(pdf, index, width_px),
    }
    .map_err(|e| format!("render page {page}: {e}"))
}

/// Export one page to a user-picked path (save dialog defaulting to
/// `page-042.jpg`). Returns the saved path, or `None` if cancelled.
#[tauri::command]
pub async fn editor_export_pdf_page(
    app: AppHandle,
    state: State<'_, AppState>,
    book_id: i64,
    page: usize,
    dpi: u32,
    format: PageFormat,
) -> Result<Option<String>, String> {
    let (kind, path) = editor_source(&state, book_id).await?;
    if kind != SourceKind::Pdf {
        return Err("this book's source isn't a PDF".to_string());
    }
    let bytes = tokio::task::spawn_blocking(move || -> Result<Vec<u8>, String> {
        let pdf = std::fs::read(&path).map_err(|e| format!("read {path}: {e}"))?;
        let pages = bokai::import::pdf::probe_pdf(pdf.clone())
            .map_err(|e| e.to_string())?
            .pages;
        render_page(&pdf, &pages, page, dpi, format)
    })
    .await
    .map_err(|e| e.to_string())??;

    let (tx, rx) = oneshot::channel();
    app.dialog()
        .file()
        .set_file_name(format!("page-{page:03}.{}", format.ext()))
        .save_file(move |path| {
            let _ = tx.send(path);
        });
    let Some(dest) = rx.await.map_err(|e| e.to_string())? else {
        return Ok(None); // cancelled
    };
    let dest = PathBuf::from(dest.to_string());
    std::fs::write(&dest, &bytes).map_err(|e| format!("write {}: {e}", dest.display()))?;
    Ok(Some(dest.to_string_lossy().to_string()))
}

/// Export `pages` (1-based) into `dir`, each named `page-042.jpg` — zero-padded
/// to the book's page count so a directory listing sorts in reading order.
#[tauri::command]
pub async fn editor_export_pdf_pages(
    state: State<'_, AppState>,
    book_id: i64,
    pages: Vec<usize>,
    dir: String,
    dpi: u32,
    format: PageFormat,
) -> Result<ExportImagesResult, String> {
    let (kind, path) = editor_source(&state, book_id).await?;
    if kind != SourceKind::Pdf {
        return Err("this book's source isn't a PDF".to_string());
    }
    if pages.is_empty() {
        return Err("no pages selected".to_string());
    }
    let dest_dir = PathBuf::from(&dir);
    let count = tokio::task::spawn_blocking(move || -> Result<usize, String> {
        let pdf = std::fs::read(&path).map_err(|e| format!("read {path}: {e}"))?;
        let geom = bokai::import::pdf::probe_pdf(pdf.clone())
            .map_err(|e| e.to_string())?
            .pages;
        std::fs::create_dir_all(&dest_dir)
            .map_err(|e| format!("create {}: {e}", dest_dir.display()))?;

        let width = geom.len().to_string().len(); // "570" -> page-001.jpg
        for &page in &pages {
            let bytes = render_page(&pdf, &geom, page, dpi, format)?;
            let out = dest_dir.join(format!("page-{page:0width$}.{}", format.ext()));
            std::fs::write(&out, &bytes).map_err(|e| format!("write {}: {e}", out.display()))?;
        }
        Ok(pages.len())
    })
    .await
    .map_err(|e| e.to_string())??;
    Ok(ExportImagesResult { dir, count })
}

/// Reduce an image's name to a filesystem-safe stem: keep ASCII alphanumerics
/// plus `.`/`-`/`_`, collapse the rest to `_` (so a KFX `resource/rsrc7` →
/// `resource_rsrc7`). Falls back to `image` when nothing printable survives.
fn sanitize_filename(name: &str) -> String {
    let mapped: String = name
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || matches!(c, '.' | '-' | '_') {
                c
            } else {
                '_'
            }
        })
        .collect();
    let trimmed = mapped.trim_matches('_');
    if trimmed.is_empty() {
        "image".to_string()
    } else {
        trimmed.to_string()
    }
}

/// Validate-only TOC verdict for the top-bar chip (no proposal — cheaper than
/// [`read_toc_detail`], which also parses the Contents page). Format-sniffed by
/// [`toc_validate::validate`]. `None` on a read or parse error. Sync — call
/// inside `spawn_blocking`.
fn compute_toc(source_path: &str, kind: SourceKind) -> Option<EditorToc> {
    let bytes = std::fs::read(source_path).ok()?;
    if kind == SourceKind::Pdf {
        return Some(pdf_toc_summary(&bytes)?.0);
    }
    let audit = toc_validate::validate(&bytes).ok()?;
    Some(EditorToc {
        verdict: audit.verdict.as_str().to_string(),
        nav_count: audit.nav_count,
        nav_chapters: audit.nav_chapters,
        contents_links: audit.contents_links,
        headings: audit.headings,
        section_heads: audit.section_heads,
    })
}

/// PDF TOC summary: the verdict chip plus the parsed outline and page count.
///
/// PDF gets its own verdict rather than going through `validate::source::toc`,
/// which is deliberate: that detector weighs a declared TOC against in-book
/// evidence (Contents-page links, styled headings, bare chapter markers) that a
/// PDF's object model simply doesn't carry. With no ground truth to compare
/// against, the only honest signal is presence — an outline exists or it doesn't.
/// So `SPARSE` means "no outline" (the case the editor exists to fix) and `OK`
/// means the PDF declares one; we never claim a PDF's outline is *deficient*,
/// because we have no basis to.
fn pdf_toc_summary(bytes: &[u8]) -> Option<(EditorToc, Vec<PdfOutlineItem>, usize)> {
    let doc = bokai::import::probe_pdf(bytes.to_vec()).ok()?;
    let count = count_outline(&doc.outline);
    Some((
        EditorToc {
            verdict: toc_verdict(count).to_string(),
            nav_count: count,
            nav_chapters: count,
            contents_links: 0,
            headings: 0,
            section_heads: 0,
        },
        doc.outline,
        doc.pages.len(),
    ))
}

/// A PDF's TOC verdict is presence-based: it either declares an outline or it
/// doesn't. Unlike EPUB and KFX there is no in-book evidence — no headings, no
/// contents page — to judge an existing outline as *deficient* against, so
/// "OK" is the ceiling and the panel never proposes a repair.
fn toc_verdict(count: usize) -> &'static str {
    if count == 0 { "SPARSE" } else { "OK" }
}

/// Total entries in an outline tree, all levels.
fn count_outline(items: &[PdfOutlineItem]) -> usize {
    items.iter().map(|i| 1 + count_outline(&i.children)).sum()
}

/// Flattened outline labels, indented by depth, for the "Currently declared"
/// list — so a nested PDF outline reads as a tree rather than a flat run.
fn flatten_outline_labels(items: &[PdfOutlineItem], depth: usize, out: &mut Vec<String>) {
    for i in items {
        out.push(format!(
            "{}{} — p.{}",
            "  ".repeat(depth),
            i.title,
            i.page_index + 1
        ));
        flatten_outline_labels(&i.children, depth + 1, out);
    }
}

/// Full TOC panel state — verdict + current labels + the proposal (nesting
/// preserved). Format-sniffed (EPUB zip vs KFX container). Sync (reads + parses
/// the source); call inside `spawn_blocking`.
fn read_toc_detail(source_path: &str, kind: SourceKind) -> Result<EditorTocDetail, String> {
    let bytes = std::fs::read(source_path).map_err(|e| format!("read {source_path}: {e}"))?;

    // PDF: no proposer, so the panel starts from the book's existing outline (or
    // blank) and the user authors it by hand.
    if kind == SourceKind::Pdf {
        let (summary, outline, page_count) =
            pdf_toc_summary(&bytes).ok_or_else(|| "couldn't read the PDF".to_string())?;
        let mut current = Vec::new();
        flatten_outline_labels(&outline, 0, &mut current);
        let note = outline.is_empty().then(|| {
            "This PDF has no table of contents. Add entries below — each one \
             needs a title and the page it jumps to."
                .to_string()
        });
        return Ok(EditorTocDetail {
            verdict: summary.verdict,
            nav_count: summary.nav_count,
            nav_chapters: summary.nav_chapters,
            current,
            proposed: outline.iter().map(TocEntryDto::from_pdf).collect(),
            note,
            page_count: Some(page_count),
            can_auto_repair: false,
        });
    }

    let audit = toc_validate::validate(&bytes)?;
    let no_contents = "No chapter list found in the book's Contents page or headings.";
    let (proposed, note): (Vec<TocEntryDto>, Option<String>) = if bytes.starts_with(b"PK") {
        match epub_toc::propose_toc(&bytes) {
            Ok(entries) if !entries.is_empty() => {
                (entries.iter().map(TocEntryDto::from_epub).collect(), None)
            }
            Ok(_) => (Vec::new(), Some(no_contents.to_string())),
            Err(e) => (
                Vec::new(),
                Some(format!("Couldn't auto-derive chapters: {e}")),
            ),
        }
    } else {
        match toc_repair::propose_toc(&bytes) {
            Ok(entries) if !entries.is_empty() => {
                (entries.iter().map(TocEntryDto::from_kfx).collect(), None)
            }
            Ok(_) => (Vec::new(), Some(no_contents.to_string())),
            Err(e) => (
                Vec::new(),
                Some(format!("Couldn't auto-derive chapters: {e}")),
            ),
        }
    };
    Ok(EditorTocDetail {
        verdict: audit.verdict.as_str().to_string(),
        nav_count: audit.nav_count,
        nav_chapters: audit.nav_chapters,
        current: audit.nav_labels,
        proposed,
        note,
        page_count: None,
        can_auto_repair: true,
    })
}

/// Dispatch a save commit to the source format's seam.
async fn commit_edited_source(
    state: &State<'_, AppState>,
    book_id: i64,
    kind: SourceKind,
    path: &str,
    new_bytes: Vec<u8>,
) -> Result<(), String> {
    report_edit_regressions(kind, path, &new_bytes).await;
    match kind {
        SourceKind::Kfx => commit_edited_kfx(state, book_id, path, new_bytes).await,
        // EPUB and PDF are both "source file that derives a KFX", so they share
        // one seam: replace the source, let reconvert rebuild the KFX.
        SourceKind::Epub | SourceKind::Pdf => commit_replaced_source(path, new_bytes).await,
    }
}

/// The differential validation gate for every editor save: log the error-level
/// findings this edit *introduced*. A directly-imported EPUB is usually invalid
/// before we touch it and no single edit can fix that, so "clean" is the wrong
/// bar — the checkable obligation is that an edit must not *add* a defect. (An
/// EPUB-3-only `properties="cover-image"` injected into an EPUB 2 package was
/// exactly this class of bug.) Non-blocking, like every other validation seam:
/// it reports and the save proceeds.
///
/// EPUB only — `bokai::validate::source::added_errors` sniffs the format and
/// would run the KFX checks for a KFX, which is a separate obligation with its
/// own (much slower) pass.
async fn report_edit_regressions(kind: SourceKind, path: &str, new_bytes: &[u8]) {
    if kind != SourceKind::Epub {
        return;
    }
    let (src, after) = (path.to_string(), new_bytes.to_vec());
    let added = tokio::task::spawn_blocking(move || {
        let before = std::fs::read(&src).ok()?;
        Some(bokai::validate::source::added_errors(&before, &after))
    })
    .await;
    let Ok(Some(added)) = added else { return };
    if added.is_empty() {
        return;
    }
    eprintln!(
        "[sidle/editor] edit of {path} introduced {} new error finding(s) — saved anyway:",
        added.len()
    );
    for finding in &added {
        eprintln!(
            "  [{}] {}/{} @ {}: {}",
            finding.severity.as_str(),
            finding.check,
            finding.rule,
            finding.location,
            finding.message
        );
    }
}

/// The KFX save seam. Commit `new_bytes` to `kfx_path` in place: back up the
/// original, write atomically (temp + rename), preserve the frozen `kfx_sha256`
/// device identity, and drop the backup once the file is settled. Rolls the file
/// back from the backup if the replace fails partway. The caller handles the
/// library-row sync, the derived-EPUB reconvert, and the reader eviction.
async fn commit_edited_kfx(
    state: &AppState,
    book_id: i64,
    kfx_path: &str,
    new_bytes: Vec<u8>,
) -> Result<(), String> {
    let path = kfx_path.to_string();
    let new_sha = tokio::task::spawn_blocking(move || -> Result<String, String> {
        let target = Path::new(&path);
        let backup = sibling(target, "editbak");
        let temp = sibling(target, "editing");

        // Back up the original — required for rollback, so a failure here aborts
        // before we've touched the live file.
        std::fs::copy(target, &backup).map_err(|e| format!("back up {}: {e}", target.display()))?;

        // Write the new bytes to a sibling temp, then atomically rename over the
        // target so a crash mid-write can't leave a truncated KFX.
        if let Err(e) = std::fs::write(&temp, &new_bytes) {
            let _ = std::fs::remove_file(&backup);
            return Err(format!("write {}: {e}", temp.display()));
        }
        if let Err(e) = std::fs::rename(&temp, target) {
            let _ = std::fs::remove_file(&temp);
            let _ = std::fs::copy(&backup, target); // best-effort restore
            let _ = std::fs::remove_file(&backup);
            return Err(format!("replace {}: {e}", target.display()));
        }

        let sha = sidle_core::library::import::sha256_of_file(target).map_err(|e| e.to_string())?;
        let _ = std::fs::remove_file(&backup); // settled — tidy the backup
        Ok(sha)
    })
    .await
    .map_err(|e| e.to_string())??;

    // COALESCE keeps the existing `kfx_sha256`, so the on-device filename and
    // annotation-sync identity stay stable even though the bytes changed.
    {
        let conn = state.db.lock().await;
        db::set_kfx_path_and_sha(&conn, book_id, kfx_path, &new_sha).map_err(|e| e.to_string())?;
    }
    Ok(())
}

/// The save seam for a source file that *derives* the KFX — EPUB and PDF. Back
/// up the source, atomically replace it, and drop the backup once settled
/// (rolling back on a failed replace). Unlike the KFX seam it touches **no** DB
/// identity: `sha256` (the storage key) and `kfx_sha256` (the on-device file's
/// hash) both stay frozen. The reader/device file is the *derived* KFX, which the
/// caller's `enqueue_reconvert` regenerates — and that path re-freezes
/// `kfx_sha256` via COALESCE, so device-sync identity is preserved exactly as for
/// a KFX-source edit.
async fn commit_replaced_source(source_path: &str, new_bytes: Vec<u8>) -> Result<(), String> {
    let path = source_path.to_string();
    tokio::task::spawn_blocking(move || -> Result<(), String> {
        let target = Path::new(&path);
        let backup = sibling(target, "editbak");
        let temp = sibling(target, "editing");

        std::fs::copy(target, &backup).map_err(|e| format!("back up {}: {e}", target.display()))?;
        if let Err(e) = std::fs::write(&temp, &new_bytes) {
            let _ = std::fs::remove_file(&backup);
            return Err(format!("write {}: {e}", temp.display()));
        }
        if let Err(e) = std::fs::rename(&temp, target) {
            let _ = std::fs::remove_file(&temp);
            let _ = std::fs::copy(&backup, target); // best-effort restore
            let _ = std::fs::remove_file(&backup);
            return Err(format!("replace {}: {e}", target.display()));
        }
        let _ = std::fs::remove_file(&backup); // settled — tidy the backup
        Ok(())
    })
    .await
    .map_err(|e| e.to_string())?
}

/// `path` with an extra dot-suffix, e.g. `book.kfx` + `"editbak"` →
/// `book.kfx.editbak`. Kept in the same directory as `path` so the temp→target
/// rename is atomic (same filesystem).
fn sibling(path: &Path, suffix: &str) -> PathBuf {
    let mut name = path.file_name().unwrap_or_default().to_os_string();
    name.push(".");
    name.push(suffix);
    path.with_file_name(name)
}

/// Trim a submitted optional string; an empty result clears the field (`None`).
fn trim_opt(s: Option<String>) -> Option<String> {
    s.map(|s| s.trim().to_string()).filter(|s| !s.is_empty())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The cheapest thing `read_toc_detail` will accept for the PDF branch: a
    /// structurally valid PDF with one blank page and no outline. It exists so
    /// the panel has something to open — the assertions below are about our
    /// editor policy, not about PDF. The `xref` offsets are absolute, so edit
    /// the body only by regenerating the whole literal.
    const MINIMAL_INPUT: &[u8] = b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] >>\nendobj\n4 0 obj\n<< /Title (Tiny Test PDF) /Author (A. Tester) >>\nendobj\nxref\n0 5\n0000000000 65535 f \n0000000015 00000 n \n0000000064 00000 n \n0000000121 00000 n \n0000000192 00000 n \ntrailer\n<< /Size 5 /Root 1 0 R /Info 4 0 R >>\nstartxref\n256\n%%EOF\n";

    #[test]
    fn source_format_from_kind() {
        assert_eq!(source_format(Some("kfx_to_epub")), "kfx");
        assert_eq!(source_format(Some("epub_to_kfx")), "epub");
        assert_eq!(source_format(Some("pdf_to_kfx")), "pdf");
        // Missing kind falls back to the EPUB-source default (matches the frontend).
        assert_eq!(source_format(None), "epub");
    }

    /// A PDF point is 1/72", so a 300-dpi render is the page's point width times
    /// 300/72. The Images panel shows the user these same numbers before they
    /// export, computed independently in `pageDims()` — so this pins the maths
    /// both sides have to agree on.
    #[test]
    fn export_width_follows_dpi_from_the_page_size() {
        // US Letter, 612pt wide: the textbook cases.
        assert_eq!(export_width_px(612.0, 72), 612, "72 dpi is 1px per point");
        assert_eq!(export_width_px(612.0, 300), 2550);
        assert_eq!(export_width_px(612.0, 600), 5100);
        // A bunko page at 300 dpi — the real scanned-novel case.
        assert_eq!(export_width_px(342.7, 300), 1428);
    }

    /// The rasterizer refuses a bitmap wider than a `u16`, so an absurd page or
    /// DPI has to be clamped before it gets there — and a degenerate page must
    /// not render an empty bitmap.
    #[test]
    fn export_width_is_clamped_at_both_ends() {
        assert_eq!(
            export_width_px(0.0, 300),
            1,
            "a zero-width page still renders"
        );
        assert_eq!(
            export_width_px(612.0, 0),
            1,
            "0 dpi floors rather than empties"
        );
        assert_eq!(export_width_px(f32::NAN, 300), 1);
        assert_eq!(
            export_width_px(1_000_000.0, 600),
            20_000,
            "clamped, not overflowed"
        );
        // A0 at 600 dpi stays under the cap — the bound is generous, not tight.
        assert!(export_width_px(2384.0, 600) < 20_000);
    }

    /// The rail's capability gate: every editable source backs these four, and
    /// `text` is not one of them — the rail offers a Text button, and nothing
    /// but this list keeps it dark.
    #[test]
    fn panels_cover_every_built_capability_but_not_text() {
        let p = editor_panels();
        for want in ["metadata", "toc", "cover", "images"] {
            assert!(p.contains(&want.to_string()), "{want} panel is backed");
        }
        assert!(
            !p.contains(&"text".to_string()),
            "no text-edit primitive yet"
        );
    }

    /// The PDF DTO boundary: the panel speaks 1-based page numbers, the primitive
    /// speaks 0-based indices, and the tree survives a round-trip.
    #[test]
    fn pdf_toc_dto_roundtrips_page_numbers_and_nesting() {
        let outline = [PdfOutlineItem {
            title: "Part I".into(),
            page_index: 0,
            children: vec![PdfOutlineItem {
                title: "Chapter 1".into(),
                page_index: 41,
                children: vec![],
            }],
        }];
        let dto: Vec<TocEntryDto> = outline.iter().map(TocEntryDto::from_pdf).collect();
        assert_eq!(dto[0].page, 1, "0-based index 0 shows as page 1");
        assert_eq!(dto[0].children[0].page, 42);

        let back: Vec<PdfOutlineItem> = dto.into_iter().map(TocEntryDto::into_pdf).collect();
        assert_eq!(back[0].page_index, 0);
        assert_eq!(back[0].children[0].page_index, 41);
        assert_eq!(back[0].children[0].title, "Chapter 1");
    }

    /// A page of 0 (a panel row never touched) clamps to page 1 rather than
    /// underflowing to usize::MAX.
    #[test]
    fn pdf_dto_page_zero_clamps_to_first_page() {
        let dto = TocEntryDto {
            label: "  Spacey  ".into(),
            eid: 0,
            href: String::new(),
            page: 0,
            children: vec![],
        };
        let item = dto.into_pdf();
        assert_eq!(item.page_index, 0);
        assert_eq!(item.title, "Spacey", "labels are trimmed at the boundary");
    }

    /// PDF's TOC verdict is presence-based: an outline exists or it doesn't. We
    /// never claim a PDF outline is *deficient* — there's no in-book evidence to
    /// judge it against. Reading the outline out of a file is the conversion
    /// library's job and is tested there; this is only our rule over the count.
    #[test]
    fn pdf_toc_verdict_reflects_presence() {
        assert_eq!(toc_verdict(0), "SPARSE");
        assert_eq!(toc_verdict(1), "OK");
        assert_eq!(toc_verdict(99), "OK", "no ceiling above OK for a PDF");
    }

    /// The panel's "Currently declared" list shows nesting and page numbers.
    #[test]
    fn outline_labels_flatten_with_depth_and_page() {
        let outline = [PdfOutlineItem {
            title: "Part I".into(),
            page_index: 0,
            children: vec![PdfOutlineItem {
                title: "Chapter 1".into(),
                page_index: 4,
                children: vec![],
            }],
        }];
        let mut out = Vec::new();
        flatten_outline_labels(&outline, 0, &mut out);
        assert_eq!(out, vec!["Part I — p.1", "  Chapter 1 — p.5"]);
        assert_eq!(count_outline(&outline), 2);
    }

    /// `read_toc_detail` puts a PDF panel into hand-authoring mode: page count
    /// present, auto-repair off, and a note when the book has no TOC.
    #[test]
    fn pdf_toc_detail_is_hand_authoring_mode() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("t.pdf");
        std::fs::write(&path, MINIMAL_INPUT).expect("write");

        let detail = read_toc_detail(path.to_str().unwrap(), SourceKind::Pdf).expect("detail");
        assert_eq!(detail.page_count, Some(1));
        assert!(!detail.can_auto_repair, "PDF has no proposer");
        assert!(detail.proposed.is_empty());
        assert!(detail.note.is_some(), "explains that entries must be added");
        assert_eq!(detail.verdict, "SPARSE");
    }

    #[test]
    fn sibling_appends_suffix_in_same_dir() {
        let p = Path::new("/books/abc/book.kfx");
        assert_eq!(
            sibling(p, "editbak"),
            Path::new("/books/abc/book.kfx.editbak")
        );
        assert_eq!(
            sibling(p, "editing"),
            Path::new("/books/abc/book.kfx.editing")
        );
    }

    #[test]
    fn trim_opt_clears_blank() {
        assert_eq!(
            trim_opt(Some("  Shinchosha ".into())),
            Some("Shinchosha".into())
        );
        assert_eq!(trim_opt(Some("   ".into())), None);
        assert_eq!(trim_opt(Some(String::new())), None);
        assert_eq!(trim_opt(None), None);
    }

    #[test]
    fn toc_dto_round_trips_nesting_faithfully() {
        // A nested source (Part → chapters) must survive DTO → wire → TocEntry
        // with its shape intact: no flatten, no re-nest.
        let src = [
            KfxTocEntry {
                label: "Part I".into(),
                eid: 1,
                children: vec![KfxTocEntry::new("Ch 1", 2), KfxTocEntry::new("Ch 2", 3)],
            },
            KfxTocEntry::new("Afterword", 4),
        ];
        let dto: Vec<TocEntryDto> = src.iter().map(TocEntryDto::from_kfx).collect();
        let back: Vec<KfxTocEntry> = dto.into_iter().map(TocEntryDto::into_kfx).collect();

        assert_eq!(back.len(), 2);
        assert_eq!(back[0].label, "Part I");
        assert_eq!(back[0].eid, 1);
        assert_eq!(back[0].children.len(), 2);
        assert_eq!(back[0].children[1].label, "Ch 2");
        assert_eq!(back[0].children[1].eid, 3);
        // The Afterword stays a top-level leaf.
        assert_eq!(back[1].label, "Afterword");
        assert!(back[1].children.is_empty());

        // A flat source stays flat.
        let flat = [KfxTocEntry::new("One", 10), KfxTocEntry::new("Two", 20)];
        let back: Vec<KfxTocEntry> = flat
            .iter()
            .map(TocEntryDto::from_kfx)
            .map(TocEntryDto::into_kfx)
            .collect();
        assert!(back.iter().all(|e| e.children.is_empty()));
    }

    /// The EPUB path of the DTO round-trips title↔label and href faithfully.
    #[test]
    fn toc_dto_round_trips_epub_href() {
        let src = [EpubTocEntry {
            title: "Part I".into(),
            href: "OEBPS/p1.xhtml".into(),
            children: vec![EpubTocEntry::new("Ch 1", "OEBPS/c1.xhtml#h1")],
            play_order: None,
            target: None,
        }];
        let dto: Vec<TocEntryDto> = src.iter().map(TocEntryDto::from_epub).collect();
        assert_eq!(dto[0].href, "OEBPS/p1.xhtml");
        assert_eq!(dto[0].eid, 0, "EPUB entries carry no eid");
        let back: Vec<EpubTocEntry> = dto.into_iter().map(TocEntryDto::into_epub).collect();
        assert_eq!(back[0].title, "Part I");
        assert_eq!(back[0].children[0].href, "OEBPS/c1.xhtml#h1");
    }

    #[test]
    fn any_blank_label_finds_nested_blanks() {
        let ok = [KfxTocEntry::new("A", 1), KfxTocEntry::new("B", 2)];
        let ok_dto: Vec<TocEntryDto> = ok.iter().map(TocEntryDto::from_kfx).collect();
        assert!(!any_blank_label(&ok_dto));

        // A blank label buried under a Part must still be caught.
        let bad = [KfxTocEntry {
            label: "Part I".into(),
            eid: 1,
            children: vec![KfxTocEntry::new("  ", 2)],
        }];
        let bad_dto: Vec<TocEntryDto> = bad.iter().map(TocEntryDto::from_kfx).collect();
        assert!(any_blank_label(&bad_dto));
    }

    #[test]
    fn sanitize_filename_keeps_safe_chars() {
        assert_eq!(sanitize_filename("resource/rsrc7"), "resource_rsrc7");
        assert_eq!(sanitize_filename("eF"), "eF");
        assert_eq!(sanitize_filename("cover-1.2"), "cover-1.2");
        // Leading/trailing separators are trimmed; an all-symbol name falls back.
        assert_eq!(sanitize_filename("/leading"), "leading");
        assert_eq!(sanitize_filename("图片"), "image");
        assert_eq!(sanitize_filename(""), "image");
    }
}
