//! The RELAX NG, Schematron and NVDL schemas epubcheck validates against,
//! vendored from epubcheck's `src/main/resources/com/adobe/epubcheck/schema`.
//!
//! They are compiled into the binary rather than read from disk: bokai has no
//! data directory at runtime, and a validator whose grammars could go missing
//! would report a book as invalid because of its own installation. The paths
//! are the ones the schemas use to reference each other (`20/rng/content.rng`,
//! `30/mod/html5/meta.rnc`, …), so [`FILES`] doubles as the resolver's map.
//!
//! The `20/dtd` tree is vendored alongside but is not part of [`FILES`]: no
//! schema references a DTD. It is read by [`super::dtd`], which answers which
//! public identifier defines `&nbsp;`.
//!
//! Regenerate this list after re-vendoring:
//!
//! ```text
//! find bokai/src/validate/source/epub/xml/schema -type f \
//!     \( -name '*.rng' -o -name '*.rnc' -o -name '*.nvdl' -o -name '*.sch' \)
//! ```

use std::collections::HashMap;

/// Every vendored schema, as `(path, content)`.
pub static FILES: &[(&str, &str)] = &[
    (
        "20/rng/container.rng",
        include_str!("schema/20/rng/container.rng"),
    ),
    (
        "20/rng/content-svg.rng",
        include_str!("schema/20/rng/content-svg.rng"),
    ),
    (
        "20/rng/content-xhtml.rng",
        include_str!("schema/20/rng/content-xhtml.rng"),
    ),
    (
        "20/rng/content.rng",
        include_str!("schema/20/rng/content.rng"),
    ),
    (
        "20/rng/dtbook-2005-2.rng",
        include_str!("schema/20/rng/dtbook-2005-2.rng"),
    ),
    (
        "20/rng/encryption.rng",
        include_str!("schema/20/rng/encryption.rng"),
    ),
    (
        "20/rng/ncx-old.rng",
        include_str!("schema/20/rng/ncx-old.rng"),
    ),
    ("20/rng/ncx.rng", include_str!("schema/20/rng/ncx.rng")),
    ("20/rng/opf.rng", include_str!("schema/20/rng/opf.rng")),
    ("20/rng/opf12.rng", include_str!("schema/20/rng/opf12.rng")),
    ("20/rng/opf20.rng", include_str!("schema/20/rng/opf20.rng")),
    (
        "20/rng/ops/ops-switch.rng",
        include_str!("schema/20/rng/ops/ops-switch.rng"),
    ),
    (
        "20/rng/ops20-svg.nvdl",
        include_str!("schema/20/rng/ops20-svg.nvdl"),
    ),
    (
        "20/rng/ops20.nvdl",
        include_str!("schema/20/rng/ops20.nvdl"),
    ),
    ("20/rng/ops20.rng", include_str!("schema/20/rng/ops20.rng")),
    (
        "20/rng/signatures.rng",
        include_str!("schema/20/rng/signatures.rng"),
    ),
    (
        "20/rng/svg/svg-animation.rng",
        include_str!("schema/20/rng/svg/svg-animation.rng"),
    ),
    (
        "20/rng/svg/svg-animevents-attrib.rng",
        include_str!("schema/20/rng/svg/svg-animevents-attrib.rng"),
    ),
    (
        "20/rng/svg/svg-basic-clip.rng",
        include_str!("schema/20/rng/svg/svg-basic-clip.rng"),
    ),
    (
        "20/rng/svg/svg-basic-filter.rng",
        include_str!("schema/20/rng/svg/svg-basic-filter.rng"),
    ),
    (
        "20/rng/svg/svg-basic-font.rng",
        include_str!("schema/20/rng/svg/svg-basic-font.rng"),
    ),
    (
        "20/rng/svg/svg-basic-graphics-attrib.rng",
        include_str!("schema/20/rng/svg/svg-basic-graphics-attrib.rng"),
    ),
    (
        "20/rng/svg/svg-basic-structure.rng",
        include_str!("schema/20/rng/svg/svg-basic-structure.rng"),
    ),
    (
        "20/rng/svg/svg-basic-text.rng",
        include_str!("schema/20/rng/svg/svg-basic-text.rng"),
    ),
    (
        "20/rng/svg/svg-clip.rng",
        include_str!("schema/20/rng/svg/svg-clip.rng"),
    ),
    (
        "20/rng/svg/svg-conditional.rng",
        include_str!("schema/20/rng/svg/svg-conditional.rng"),
    ),
    (
        "20/rng/svg/svg-container-attrib.rng",
        include_str!("schema/20/rng/svg/svg-container-attrib.rng"),
    ),
    (
        "20/rng/svg/svg-core-attrib.rng",
        include_str!("schema/20/rng/svg/svg-core-attrib.rng"),
    ),
    (
        "20/rng/svg/svg-cursor.rng",
        include_str!("schema/20/rng/svg/svg-cursor.rng"),
    ),
    (
        "20/rng/svg/svg-datatypes.rng",
        include_str!("schema/20/rng/svg/svg-datatypes.rng"),
    ),
    (
        "20/rng/svg/svg-docevents-attrib.rng",
        include_str!("schema/20/rng/svg/svg-docevents-attrib.rng"),
    ),
    (
        "20/rng/svg/svg-extensibility.rng",
        include_str!("schema/20/rng/svg/svg-extensibility.rng"),
    ),
    (
        "20/rng/svg/svg-extresources-attrib.rng",
        include_str!("schema/20/rng/svg/svg-extresources-attrib.rng"),
    ),
    (
        "20/rng/svg/svg-filter.rng",
        include_str!("schema/20/rng/svg/svg-filter.rng"),
    ),
    (
        "20/rng/svg/svg-font.rng",
        include_str!("schema/20/rng/svg/svg-font.rng"),
    ),
    (
        "20/rng/svg/svg-gradient.rng",
        include_str!("schema/20/rng/svg/svg-gradient.rng"),
    ),
    (
        "20/rng/svg/svg-graphevents-attrib.rng",
        include_str!("schema/20/rng/svg/svg-graphevents-attrib.rng"),
    ),
    (
        "20/rng/svg/svg-graphics-attrib.rng",
        include_str!("schema/20/rng/svg/svg-graphics-attrib.rng"),
    ),
    (
        "20/rng/svg/svg-hyperlink.rng",
        include_str!("schema/20/rng/svg/svg-hyperlink.rng"),
    ),
    (
        "20/rng/svg/svg-image.rng",
        include_str!("schema/20/rng/svg/svg-image.rng"),
    ),
    (
        "20/rng/svg/svg-marker.rng",
        include_str!("schema/20/rng/svg/svg-marker.rng"),
    ),
    (
        "20/rng/svg/svg-mask.rng",
        include_str!("schema/20/rng/svg/svg-mask.rng"),
    ),
    (
        "20/rng/svg/svg-opacity-attrib.rng",
        include_str!("schema/20/rng/svg/svg-opacity-attrib.rng"),
    ),
    (
        "20/rng/svg/svg-paint-attrib.rng",
        include_str!("schema/20/rng/svg/svg-paint-attrib.rng"),
    ),
    (
        "20/rng/svg/svg-pattern.rng",
        include_str!("schema/20/rng/svg/svg-pattern.rng"),
    ),
    (
        "20/rng/svg/svg-profile.rng",
        include_str!("schema/20/rng/svg/svg-profile.rng"),
    ),
    (
        "20/rng/svg/svg-qname.rng",
        include_str!("schema/20/rng/svg/svg-qname.rng"),
    ),
    (
        "20/rng/svg/svg-script.rng",
        include_str!("schema/20/rng/svg/svg-script.rng"),
    ),
    (
        "20/rng/svg/svg-shape.rng",
        include_str!("schema/20/rng/svg/svg-shape.rng"),
    ),
    (
        "20/rng/svg/svg-structure.rng",
        include_str!("schema/20/rng/svg/svg-structure.rng"),
    ),
    (
        "20/rng/svg/svg-style.rng",
        include_str!("schema/20/rng/svg/svg-style.rng"),
    ),
    (
        "20/rng/svg/svg-text.rng",
        include_str!("schema/20/rng/svg/svg-text.rng"),
    ),
    (
        "20/rng/svg/svg-view.rng",
        include_str!("schema/20/rng/svg/svg-view.rng"),
    ),
    (
        "20/rng/svg/svg-viewport-attrib.rng",
        include_str!("schema/20/rng/svg/svg-viewport-attrib.rng"),
    ),
    (
        "20/rng/svg/svg-xlink-attrib.rng",
        include_str!("schema/20/rng/svg/svg-xlink-attrib.rng"),
    ),
    ("20/rng/svg11.rng", include_str!("schema/20/rng/svg11.rng")),
    (
        "20/rng/xenc-schema.rng",
        include_str!("schema/20/rng/xenc-schema.rng"),
    ),
    (
        "20/rng/xhtml/applet.rng",
        include_str!("schema/20/rng/xhtml/applet.rng"),
    ),
    (
        "20/rng/xhtml/attribs.rng",
        include_str!("schema/20/rng/xhtml/attribs.rng"),
    ),
    (
        "20/rng/xhtml/base.rng",
        include_str!("schema/20/rng/xhtml/base.rng"),
    ),
    (
        "20/rng/xhtml/basic-form.rng",
        include_str!("schema/20/rng/xhtml/basic-form.rng"),
    ),
    (
        "20/rng/xhtml/basic-table.rng",
        include_str!("schema/20/rng/xhtml/basic-table.rng"),
    ),
    (
        "20/rng/xhtml/bdo.rng",
        include_str!("schema/20/rng/xhtml/bdo.rng"),
    ),
    (
        "20/rng/xhtml/csismap.rng",
        include_str!("schema/20/rng/xhtml/csismap.rng"),
    ),
    (
        "20/rng/xhtml/datatypes.rng",
        include_str!("schema/20/rng/xhtml/datatypes.rng"),
    ),
    (
        "20/rng/xhtml/edit.rng",
        include_str!("schema/20/rng/xhtml/edit.rng"),
    ),
    (
        "20/rng/xhtml/events.rng",
        include_str!("schema/20/rng/xhtml/events.rng"),
    ),
    (
        "20/rng/xhtml/form.rng",
        include_str!("schema/20/rng/xhtml/form.rng"),
    ),
    (
        "20/rng/xhtml/frames.rng",
        include_str!("schema/20/rng/xhtml/frames.rng"),
    ),
    (
        "20/rng/xhtml/hypertext.rng",
        include_str!("schema/20/rng/xhtml/hypertext.rng"),
    ),
    (
        "20/rng/xhtml/iframe.rng",
        include_str!("schema/20/rng/xhtml/iframe.rng"),
    ),
    (
        "20/rng/xhtml/image.rng",
        include_str!("schema/20/rng/xhtml/image.rng"),
    ),
    (
        "20/rng/xhtml/inlstyle.rng",
        include_str!("schema/20/rng/xhtml/inlstyle.rng"),
    ),
    (
        "20/rng/xhtml/legacy.rng",
        include_str!("schema/20/rng/xhtml/legacy.rng"),
    ),
    (
        "20/rng/xhtml/link.rng",
        include_str!("schema/20/rng/xhtml/link.rng"),
    ),
    (
        "20/rng/xhtml/list.rng",
        include_str!("schema/20/rng/xhtml/list.rng"),
    ),
    (
        "20/rng/xhtml/meta.rng",
        include_str!("schema/20/rng/xhtml/meta.rng"),
    ),
    (
        "20/rng/xhtml/nameident.rng",
        include_str!("schema/20/rng/xhtml/nameident.rng"),
    ),
    (
        "20/rng/xhtml/object.rng",
        include_str!("schema/20/rng/xhtml/object.rng"),
    ),
    (
        "20/rng/xhtml/param.rng",
        include_str!("schema/20/rng/xhtml/param.rng"),
    ),
    (
        "20/rng/xhtml/pres.rng",
        include_str!("schema/20/rng/xhtml/pres.rng"),
    ),
    (
        "20/rng/xhtml/ruby.rng",
        include_str!("schema/20/rng/xhtml/ruby.rng"),
    ),
    (
        "20/rng/xhtml/script.rng",
        include_str!("schema/20/rng/xhtml/script.rng"),
    ),
    (
        "20/rng/xhtml/ssismap.rng",
        include_str!("schema/20/rng/xhtml/ssismap.rng"),
    ),
    (
        "20/rng/xhtml/struct.rng",
        include_str!("schema/20/rng/xhtml/struct.rng"),
    ),
    (
        "20/rng/xhtml/style.rng",
        include_str!("schema/20/rng/xhtml/style.rng"),
    ),
    (
        "20/rng/xhtml/table.rng",
        include_str!("schema/20/rng/xhtml/table.rng"),
    ),
    (
        "20/rng/xhtml/target.rng",
        include_str!("schema/20/rng/xhtml/target.rng"),
    ),
    (
        "20/rng/xhtml/text.rng",
        include_str!("schema/20/rng/xhtml/text.rng"),
    ),
    (
        "20/rng/xmldsig-core-schema.rng",
        include_str!("schema/20/rng/xmldsig-core-schema.rng"),
    ),
    (
        "20/sch/id-unique.sch",
        include_str!("schema/20/sch/id-unique.sch"),
    ),
    ("20/sch/ncx.sch", include_str!("schema/20/sch/ncx.sch")),
    ("20/sch/opf.sch", include_str!("schema/20/sch/opf.sch")),
    ("20/sch/xhtml.sch", include_str!("schema/20/sch/xhtml.sch")),
    (
        "30/collection-do-30.sch",
        include_str!("schema/30/collection-do-30.sch"),
    ),
    (
        "30/collection-manifest-30.sch",
        include_str!("schema/30/collection-manifest-30.sch"),
    ),
    (
        "30/datanav/datanav-xhtml.sch",
        include_str!("schema/30/datanav/datanav-xhtml.sch"),
    ),
    (
        "30/dict/dict-collection.sch",
        include_str!("schema/30/dict/dict-collection.sch"),
    ),
    (
        "30/dict/dict-opf.sch",
        include_str!("schema/30/dict/dict-opf.sch"),
    ),
    (
        "30/dict/dict-xhtml.sch",
        include_str!("schema/30/dict/dict-xhtml.sch"),
    ),
    (
        "30/dict/search-key-map.rnc",
        include_str!("schema/30/dict/search-key-map.rnc"),
    ),
    (
        "30/edupub/edu-ocf-metadata.sch",
        include_str!("schema/30/edupub/edu-ocf-metadata.sch"),
    ),
    (
        "30/edupub/edu-opf.sch",
        include_str!("schema/30/edupub/edu-opf.sch"),
    ),
    (
        "30/edupub/edu-semantics.sch",
        include_str!("schema/30/edupub/edu-semantics.sch"),
    ),
    (
        "30/edupub/edu-structure.sch",
        include_str!("schema/30/edupub/edu-structure.sch"),
    ),
    (
        "30/epub-nav-30.nvdl",
        include_str!("schema/30/epub-nav-30.nvdl"),
    ),
    (
        "30/epub-nav-30.rnc",
        include_str!("schema/30/epub-nav-30.rnc"),
    ),
    (
        "30/epub-nav-30.sch",
        include_str!("schema/30/epub-nav-30.sch"),
    ),
    (
        "30/epub-svg-30-informative.nvdl",
        include_str!("schema/30/epub-svg-30-informative.nvdl"),
    ),
    (
        "30/epub-svg-30-informative.rnc",
        include_str!("schema/30/epub-svg-30-informative.rnc"),
    ),
    (
        "30/epub-svg-30.nvdl",
        include_str!("schema/30/epub-svg-30.nvdl"),
    ),
    (
        "30/epub-svg-30.rnc",
        include_str!("schema/30/epub-svg-30.rnc"),
    ),
    (
        "30/epub-svg-30.sch",
        include_str!("schema/30/epub-svg-30.sch"),
    ),
    (
        "30/epub-xhtml-30.nvdl",
        include_str!("schema/30/epub-xhtml-30.nvdl"),
    ),
    (
        "30/epub-xhtml-30.rnc",
        include_str!("schema/30/epub-xhtml-30.rnc"),
    ),
    (
        "30/epub-xhtml-30.sch",
        include_str!("schema/30/epub-xhtml-30.sch"),
    ),
    (
        "30/idx/idx-collection.sch",
        include_str!("schema/30/idx/idx-collection.sch"),
    ),
    (
        "30/idx/idx-xhtml-index.sch",
        include_str!("schema/30/idx/idx-xhtml-index.sch"),
    ),
    (
        "30/idx/idx-xhtml.sch",
        include_str!("schema/30/idx/idx-xhtml.sch"),
    ),
    (
        "30/media-overlay-30.nvdl",
        include_str!("schema/30/media-overlay-30.nvdl"),
    ),
    (
        "30/media-overlay-30.rnc",
        include_str!("schema/30/media-overlay-30.rnc"),
    ),
    (
        "30/media-overlay-30.sch",
        include_str!("schema/30/media-overlay-30.sch"),
    ),
    (
        "30/mod/datatypes.rnc",
        include_str!("schema/30/mod/datatypes.rnc"),
    ),
    (
        "30/mod/epub-mathml3-inc.rnc",
        include_str!("schema/30/mod/epub-mathml3-inc.rnc"),
    ),
    (
        "30/mod/epub-prefix-attr.rnc",
        include_str!("schema/30/mod/epub-prefix-attr.rnc"),
    ),
    (
        "30/mod/epub-shared-inc.rnc",
        include_str!("schema/30/mod/epub-shared-inc.rnc"),
    ),
    (
        "30/mod/epub-ssml-attrs.rnc",
        include_str!("schema/30/mod/epub-ssml-attrs.rnc"),
    ),
    (
        "30/mod/epub-svg-forgiving-inc.rnc",
        include_str!("schema/30/mod/epub-svg-forgiving-inc.rnc"),
    ),
    (
        "30/mod/epub-svg-strict-inc.rnc",
        include_str!("schema/30/mod/epub-svg-strict-inc.rnc"),
    ),
    (
        "30/mod/epub-switch.rnc",
        include_str!("schema/30/mod/epub-switch.rnc"),
    ),
    (
        "30/mod/epub-trigger.rnc",
        include_str!("schema/30/mod/epub-trigger.rnc"),
    ),
    (
        "30/mod/epub-type-attr.rnc",
        include_str!("schema/30/mod/epub-type-attr.rnc"),
    ),
    (
        "30/mod/epub-xhtml-inc.rnc",
        include_str!("schema/30/mod/epub-xhtml-inc.rnc"),
    ),
    (
        "30/mod/epub-xhtml-integration.rnc",
        include_str!("schema/30/mod/epub-xhtml-integration.rnc"),
    ),
    (
        "30/mod/epub-xhtml-svg-mathml.rnc",
        include_str!("schema/30/mod/epub-xhtml-svg-mathml.rnc"),
    ),
    (
        "30/mod/html5/applications.rnc",
        include_str!("schema/30/mod/html5/applications.rnc"),
    ),
    (
        "30/mod/html5/aria.rnc",
        include_str!("schema/30/mod/html5/aria.rnc"),
    ),
    (
        "30/mod/html5/assertions.sch",
        include_str!("schema/30/mod/html5/assertions.sch"),
    ),
    (
        "30/mod/html5/block.rnc",
        include_str!("schema/30/mod/html5/block.rnc"),
    ),
    (
        "30/mod/html5/common.rnc",
        include_str!("schema/30/mod/html5/common.rnc"),
    ),
    (
        "30/mod/html5/core-scripting.rnc",
        include_str!("schema/30/mod/html5/core-scripting.rnc"),
    ),
    (
        "30/mod/html5/data.rnc",
        include_str!("schema/30/mod/html5/data.rnc"),
    ),
    (
        "30/mod/html5/embed.rnc",
        include_str!("schema/30/mod/html5/embed.rnc"),
    ),
    (
        "30/mod/html5/form-datatypes.rnc",
        include_str!("schema/30/mod/html5/form-datatypes.rnc"),
    ),
    (
        "30/mod/html5/html5.rnc",
        include_str!("schema/30/mod/html5/html5.rnc"),
    ),
    (
        "30/mod/html5/html5exclusions.rnc",
        include_str!("schema/30/mod/html5/html5exclusions.rnc"),
    ),
    (
        "30/mod/html5/media.rnc",
        include_str!("schema/30/mod/html5/media.rnc"),
    ),
    (
        "30/mod/html5/meta.rnc",
        include_str!("schema/30/mod/html5/meta.rnc"),
    ),
    (
        "30/mod/html5/microdata.rnc",
        include_str!("schema/30/mod/html5/microdata.rnc"),
    ),
    (
        "30/mod/html5/phrase.rnc",
        include_str!("schema/30/mod/html5/phrase.rnc"),
    ),
    (
        "30/mod/html5/rdfa.rnc",
        include_str!("schema/30/mod/html5/rdfa.rnc"),
    ),
    (
        "30/mod/html5/revision.rnc",
        include_str!("schema/30/mod/html5/revision.rnc"),
    ),
    (
        "30/mod/html5/ruby.rnc",
        include_str!("schema/30/mod/html5/ruby.rnc"),
    ),
    (
        "30/mod/html5/sectional.rnc",
        include_str!("schema/30/mod/html5/sectional.rnc"),
    ),
    (
        "30/mod/html5/structural.rnc",
        include_str!("schema/30/mod/html5/structural.rnc"),
    ),
    (
        "30/mod/html5/tables.rnc",
        include_str!("schema/30/mod/html5/tables.rnc"),
    ),
    (
        "30/mod/html5/web-components.rnc",
        include_str!("schema/30/mod/html5/web-components.rnc"),
    ),
    (
        "30/mod/html5/web-forms-scripting.rnc",
        include_str!("schema/30/mod/html5/web-forms-scripting.rnc"),
    ),
    (
        "30/mod/html5/web-forms.rnc",
        include_str!("schema/30/mod/html5/web-forms.rnc"),
    ),
    (
        "30/mod/html5/web-forms2-scripting.rnc",
        include_str!("schema/30/mod/html5/web-forms2-scripting.rnc"),
    ),
    (
        "30/mod/html5/web-forms2.rnc",
        include_str!("schema/30/mod/html5/web-forms2.rnc"),
    ),
    (
        "30/mod/html5/xhtml5.rnc",
        include_str!("schema/30/mod/html5/xhtml5.rnc"),
    ),
    (
        "30/mod/id-unique.sch",
        include_str!("schema/30/mod/id-unique.sch"),
    ),
    (
        "30/mod/mathml/mathml3-common.rnc",
        include_str!("schema/30/mod/mathml/mathml3-common.rnc"),
    ),
    (
        "30/mod/mathml/mathml3-content.rnc",
        include_str!("schema/30/mod/mathml/mathml3-content.rnc"),
    ),
    (
        "30/mod/mathml/mathml3-inc.rnc",
        include_str!("schema/30/mod/mathml/mathml3-inc.rnc"),
    ),
    (
        "30/mod/mathml/mathml3-presentation.rnc",
        include_str!("schema/30/mod/mathml/mathml3-presentation.rnc"),
    ),
    (
        "30/mod/mathml/mathml3-strict-content.rnc",
        include_str!("schema/30/mod/mathml/mathml3-strict-content.rnc"),
    ),
    (
        "30/mod/mathml/mathml3.rnc",
        include_str!("schema/30/mod/mathml/mathml3.rnc"),
    ),
    (
        "30/mod/security/Lenient-Encryption11-ghc.rnc",
        include_str!("schema/30/mod/security/Lenient-Encryption11-ghc.rnc"),
    ),
    (
        "30/mod/security/Lenient-Encryption11.rnc",
        include_str!("schema/30/mod/security/Lenient-Encryption11.rnc"),
    ),
    (
        "30/mod/security/Lenient-Signature-exclusiveC14N.rnc",
        include_str!("schema/30/mod/security/Lenient-Signature-exclusiveC14N.rnc"),
    ),
    (
        "30/mod/security/Lenient-Signature11-properties-exclusiveC14N.rnc",
        include_str!("schema/30/mod/security/Lenient-Signature11-properties-exclusiveC14N.rnc"),
    ),
    (
        "30/mod/security/Lenient-Signature11-properties.rnc",
        include_str!("schema/30/mod/security/Lenient-Signature11-properties.rnc"),
    ),
    (
        "30/mod/security/Lenient-Signature11.rnc",
        include_str!("schema/30/mod/security/Lenient-Signature11.rnc"),
    ),
    (
        "30/mod/security/Strict-Encryption.rnc",
        include_str!("schema/30/mod/security/Strict-Encryption.rnc"),
    ),
    (
        "30/mod/security/Strict-Signature.rnc",
        include_str!("schema/30/mod/security/Strict-Signature.rnc"),
    ),
    (
        "30/mod/security/exc-c14n.rnc",
        include_str!("schema/30/mod/security/exc-c14n.rnc"),
    ),
    (
        "30/mod/security/security_any.rnc",
        include_str!("schema/30/mod/security/security_any.rnc"),
    ),
    (
        "30/mod/security/xenc-allowAnyForeign.rnc",
        include_str!("schema/30/mod/security/xenc-allowAnyForeign.rnc"),
    ),
    (
        "30/mod/security/xenc-schema-11.rnc",
        include_str!("schema/30/mod/security/xenc-schema-11.rnc"),
    ),
    (
        "30/mod/security/xenc-schema.rnc",
        include_str!("schema/30/mod/security/xenc-schema.rnc"),
    ),
    (
        "30/mod/security/xenc11-allowAnyForeign.rnc",
        include_str!("schema/30/mod/security/xenc11-allowAnyForeign.rnc"),
    ),
    (
        "30/mod/security/xmldsig-allowAnyForeign.rnc",
        include_str!("schema/30/mod/security/xmldsig-allowAnyForeign.rnc"),
    ),
    (
        "30/mod/security/xmldsig-core-schema.rnc",
        include_str!("schema/30/mod/security/xmldsig-core-schema.rnc"),
    ),
    (
        "30/mod/security/xmldsig-filter2.rnc",
        include_str!("schema/30/mod/security/xmldsig-filter2.rnc"),
    ),
    (
        "30/mod/security/xmldsig-properties-schema.rnc",
        include_str!("schema/30/mod/security/xmldsig-properties-schema.rnc"),
    ),
    (
        "30/mod/security/xmldsig11-allowAnyForeign.rnc",
        include_str!("schema/30/mod/security/xmldsig11-allowAnyForeign.rnc"),
    ),
    (
        "30/mod/security/xmldsig11-schema.rnc",
        include_str!("schema/30/mod/security/xmldsig11-schema.rnc"),
    ),
    (
        "30/mod/security/xmlsec-ghc-allowAnyForeign.rnc",
        include_str!("schema/30/mod/security/xmlsec-ghc-allowAnyForeign.rnc"),
    ),
    (
        "30/mod/security/xmlsec-ghc-schema.rnc",
        include_str!("schema/30/mod/security/xmlsec-ghc-schema.rnc"),
    ),
    (
        "30/mod/svg11/inkscape-draft.rnc",
        include_str!("schema/30/mod/svg11/inkscape-draft.rnc"),
    ),
    (
        "30/mod/svg11/inkscape.rnc",
        include_str!("schema/30/mod/svg11/inkscape.rnc"),
    ),
    (
        "30/mod/svg11/svg-animation.rnc",
        include_str!("schema/30/mod/svg11/svg-animation.rnc"),
    ),
    (
        "30/mod/svg11/svg-animevents-attrib.rnc",
        include_str!("schema/30/mod/svg11/svg-animevents-attrib.rnc"),
    ),
    (
        "30/mod/svg11/svg-basic-clip.rnc",
        include_str!("schema/30/mod/svg11/svg-basic-clip.rnc"),
    ),
    (
        "30/mod/svg11/svg-basic-filter.rnc",
        include_str!("schema/30/mod/svg11/svg-basic-filter.rnc"),
    ),
    (
        "30/mod/svg11/svg-basic-font.rnc",
        include_str!("schema/30/mod/svg11/svg-basic-font.rnc"),
    ),
    (
        "30/mod/svg11/svg-basic-graphics-attrib.rnc",
        include_str!("schema/30/mod/svg11/svg-basic-graphics-attrib.rnc"),
    ),
    (
        "30/mod/svg11/svg-basic-structure.rnc",
        include_str!("schema/30/mod/svg11/svg-basic-structure.rnc"),
    ),
    (
        "30/mod/svg11/svg-basic-text.rnc",
        include_str!("schema/30/mod/svg11/svg-basic-text.rnc"),
    ),
    (
        "30/mod/svg11/svg-clip.rnc",
        include_str!("schema/30/mod/svg11/svg-clip.rnc"),
    ),
    (
        "30/mod/svg11/svg-conditional.rnc",
        include_str!("schema/30/mod/svg11/svg-conditional.rnc"),
    ),
    (
        "30/mod/svg11/svg-container-attrib.rnc",
        include_str!("schema/30/mod/svg11/svg-container-attrib.rnc"),
    ),
    (
        "30/mod/svg11/svg-core-attrib.rnc",
        include_str!("schema/30/mod/svg11/svg-core-attrib.rnc"),
    ),
    (
        "30/mod/svg11/svg-cursor.rnc",
        include_str!("schema/30/mod/svg11/svg-cursor.rnc"),
    ),
    (
        "30/mod/svg11/svg-datatypes.rnc",
        include_str!("schema/30/mod/svg11/svg-datatypes.rnc"),
    ),
    (
        "30/mod/svg11/svg-docevents-attrib.rnc",
        include_str!("schema/30/mod/svg11/svg-docevents-attrib.rnc"),
    ),
    (
        "30/mod/svg11/svg-extensibility.rnc",
        include_str!("schema/30/mod/svg11/svg-extensibility.rnc"),
    ),
    (
        "30/mod/svg11/svg-extresources-attrib.rnc",
        include_str!("schema/30/mod/svg11/svg-extresources-attrib.rnc"),
    ),
    (
        "30/mod/svg11/svg-filter.rnc",
        include_str!("schema/30/mod/svg11/svg-filter.rnc"),
    ),
    (
        "30/mod/svg11/svg-font.rnc",
        include_str!("schema/30/mod/svg11/svg-font.rnc"),
    ),
    (
        "30/mod/svg11/svg-gradient.rnc",
        include_str!("schema/30/mod/svg11/svg-gradient.rnc"),
    ),
    (
        "30/mod/svg11/svg-graphevents-attrib.rnc",
        include_str!("schema/30/mod/svg11/svg-graphevents-attrib.rnc"),
    ),
    (
        "30/mod/svg11/svg-graphics-attrib.rnc",
        include_str!("schema/30/mod/svg11/svg-graphics-attrib.rnc"),
    ),
    (
        "30/mod/svg11/svg-hyperlink.rnc",
        include_str!("schema/30/mod/svg11/svg-hyperlink.rnc"),
    ),
    (
        "30/mod/svg11/svg-image.rnc",
        include_str!("schema/30/mod/svg11/svg-image.rnc"),
    ),
    (
        "30/mod/svg11/svg-marker.rnc",
        include_str!("schema/30/mod/svg11/svg-marker.rnc"),
    ),
    (
        "30/mod/svg11/svg-mask.rnc",
        include_str!("schema/30/mod/svg11/svg-mask.rnc"),
    ),
    (
        "30/mod/svg11/svg-opacity-attrib.rnc",
        include_str!("schema/30/mod/svg11/svg-opacity-attrib.rnc"),
    ),
    (
        "30/mod/svg11/svg-paint-attrib.rnc",
        include_str!("schema/30/mod/svg11/svg-paint-attrib.rnc"),
    ),
    (
        "30/mod/svg11/svg-pattern.rnc",
        include_str!("schema/30/mod/svg11/svg-pattern.rnc"),
    ),
    (
        "30/mod/svg11/svg-profile.rnc",
        include_str!("schema/30/mod/svg11/svg-profile.rnc"),
    ),
    (
        "30/mod/svg11/svg-qname.rnc",
        include_str!("schema/30/mod/svg11/svg-qname.rnc"),
    ),
    (
        "30/mod/svg11/svg-script.rnc",
        include_str!("schema/30/mod/svg11/svg-script.rnc"),
    ),
    (
        "30/mod/svg11/svg-shape.rnc",
        include_str!("schema/30/mod/svg11/svg-shape.rnc"),
    ),
    (
        "30/mod/svg11/svg-structure.rnc",
        include_str!("schema/30/mod/svg11/svg-structure.rnc"),
    ),
    (
        "30/mod/svg11/svg-style.rnc",
        include_str!("schema/30/mod/svg11/svg-style.rnc"),
    ),
    (
        "30/mod/svg11/svg-text.rnc",
        include_str!("schema/30/mod/svg11/svg-text.rnc"),
    ),
    (
        "30/mod/svg11/svg-view.rnc",
        include_str!("schema/30/mod/svg11/svg-view.rnc"),
    ),
    (
        "30/mod/svg11/svg-viewport-attrib.rnc",
        include_str!("schema/30/mod/svg11/svg-viewport-attrib.rnc"),
    ),
    (
        "30/mod/svg11/svg-xlink-attrib.rnc",
        include_str!("schema/30/mod/svg11/svg-xlink-attrib.rnc"),
    ),
    (
        "30/mod/svg11/svg11-basic-inc.rnc",
        include_str!("schema/30/mod/svg11/svg11-basic-inc.rnc"),
    ),
    (
        "30/mod/svg11/svg11-basic.rnc",
        include_str!("schema/30/mod/svg11/svg11-basic.rnc"),
    ),
    (
        "30/mod/svg11/svg11-inc.rnc",
        include_str!("schema/30/mod/svg11/svg11-inc.rnc"),
    ),
    (
        "30/mod/svg11/svg11-tiny-inc.rnc",
        include_str!("schema/30/mod/svg11/svg11-tiny-inc.rnc"),
    ),
    (
        "30/mod/svg11/svg11-tiny.rnc",
        include_str!("schema/30/mod/svg11/svg11-tiny.rnc"),
    ),
    (
        "30/mod/svg11/svg11.rnc",
        include_str!("schema/30/mod/svg11/svg11.rnc"),
    ),
    (
        "30/multiple-renditions/container.rnc",
        include_str!("schema/30/multiple-renditions/container.rnc"),
    ),
    (
        "30/multiple-renditions/container.sch",
        include_str!("schema/30/multiple-renditions/container.sch"),
    ),
    (
        "30/multiple-renditions/mapping.rnc",
        include_str!("schema/30/multiple-renditions/mapping.rnc"),
    ),
    (
        "30/multiple-renditions/mapping.sch",
        include_str!("schema/30/multiple-renditions/mapping.sch"),
    ),
    (
        "30/ocf-container-30.nvdl",
        include_str!("schema/30/ocf-container-30.nvdl"),
    ),
    (
        "30/ocf-container-30.rnc",
        include_str!("schema/30/ocf-container-30.rnc"),
    ),
    (
        "30/ocf-encryption-30.rnc",
        include_str!("schema/30/ocf-encryption-30.rnc"),
    ),
    (
        "30/ocf-encryption-30.sch",
        include_str!("schema/30/ocf-encryption-30.sch"),
    ),
    (
        "30/ocf-metadata-30.nvdl",
        include_str!("schema/30/ocf-metadata-30.nvdl"),
    ),
    (
        "30/ocf-metadata-30.rnc",
        include_str!("schema/30/ocf-metadata-30.rnc"),
    ),
    (
        "30/ocf-metadata-30.sch",
        include_str!("schema/30/ocf-metadata-30.sch"),
    ),
    (
        "30/ocf-signatures-30.rnc",
        include_str!("schema/30/ocf-signatures-30.rnc"),
    ),
    (
        "30/package-30.nvdl",
        include_str!("schema/30/package-30.nvdl"),
    ),
    (
        "30/package-30.rnc",
        include_str!("schema/30/package-30.rnc"),
    ),
    (
        "30/package-30.sch",
        include_str!("schema/30/package-30.sch"),
    ),
    (
        "30/previews/preview-collection.sch",
        include_str!("schema/30/previews/preview-collection.sch"),
    ),
    (
        "30/previews/preview-pub-opf.sch",
        include_str!("schema/30/previews/preview-pub-opf.sch"),
    ),
];

/// The vendored schemas as a map, for [`super::relaxng::rng::MapResolver`].
pub fn files() -> HashMap<String, String> {
    FILES
        .iter()
        .map(|(path, content)| (path.to_string(), content.to_string()))
        .collect()
}

/// One vendored schema by path, or `None` when it is not compiled in.
pub fn get(path: &str) -> Option<&'static str> {
    FILES
        .iter()
        .find(|(p, _)| *p == path)
        .map(|(_, content)| *content)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_schemas_epubcheck_uses_are_all_present() {
        // The entry points `XMLValidators` names, one per document type and
        // version. A missing one would silently disable a whole class of check.
        for path in [
            "20/rng/opf20.rng",
            "20/rng/content.rng",
            "20/rng/content-xhtml.rng",
            "20/rng/ncx.rng",
            "20/rng/container.rng",
            "20/rng/ops20.nvdl",
            "20/sch/opf.sch",
            "20/sch/ncx.sch",
            "20/sch/xhtml.sch",
            "20/sch/id-unique.sch",
            "30/package-30.rnc",
            "30/package-30.sch",
            "30/epub-xhtml-30.rnc",
            "30/epub-xhtml-30.sch",
            "30/epub-nav-30.rnc",
            "30/epub-nav-30.sch",
            "30/epub-svg-30.rnc",
            "30/media-overlay-30.rnc",
        ] {
            assert!(get(path).is_some_and(|c| !c.is_empty()), "missing {path}");
        }
    }

    #[test]
    fn every_referenced_grammar_resolves() {
        // A grammar that references a file we did not vendor would fail to
        // compile at run time, which is the failure mode hardest to notice.
        let map = files();
        for (path, content) in FILES {
            if !path.ends_with(".rng") {
                continue;
            }
            for href in content
                .split("href=\"")
                .skip(1)
                .filter_map(|s| s.split('"').next())
            {
                let target = super::super::relaxng::rng::join_relative(path, href);
                assert!(
                    map.contains_key(&target),
                    "{path} references {href} → {target}, which is not vendored"
                );
            }
        }
    }
}
